- README.md
- helmexec/exec.go
- main.go
- state/state.go
Add support for the following flags:
- `--kube-context`: set what kube-context should be passed down to helm
- `charts --values`: add additional value files to the existing list of value files (for use when using overrides for different environments during CI)
- in the Charts.yml file added a new property `env` for environment vars. It's exactly the same as the `set` property but all the value fields are run through `os.Getenv` to resolve their values. Needed this for using secrets in our CI system.
Note: this is my first time working with Go so any and all feedback welcome!
> Environment Variable Support

- helmexec/exec.go
If the chart is in directory, for example, `./my/chart` the `helmfile -f my.yaml sync` will fail.
This PR will check if the chart starts with `./` or `../` and will transform it in a full path of the chart directory.
> Accept chart in a local path

- main.go
`helmfile` returns exit code `0` even when an executed `helm` command fails.
```
$ helmfile --kube-context BAD_CONTEXT --file test.yaml sync
exec: helm repo update --kube-context BAD_CONTEXT
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
Writing to ~/.helm/repository/cache/stable-index.yaml
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
exec: helm upgrade --install test stable/traefik --namespace kube-system --values values.yaml --kube-context BAD_CONTEXT
Error: could not get kubernetes config for context 'BAD_CONTEXT': context "BAD_CONTEXT" does not exist
$ echo $?
0
```
```
$ helmfile --kube-context BAD_CONTEXT --file test.yaml sync
exec: helm repo update --kube-context BAD_CONTEXT …
```
> Return exit code from helm

- README.md
- helmexec/exec.go
- helmexec/helmexec.go
- main.go
- state/state.go
This allows the execution of the `helm diff` plugin for the entire state file, which for us makes it very easy to visualize the configuration drift of a given environment for auditing and greater confidence in the deployment similar to a `terraform plan` on an environment. 
NOTE: 
- Simple copy-paste for the most part from sync job.  I had started down
the path of adding in a meta PluginCommand directive and trying to make it
more modular, but in the end there are some small differences between
the execution that were a bit difficult to model and it just got ugly.
Figured keeping it simple would be easier to manage. 
If a more extensible form of this is desired I can work on modeling that a bit to make it easier to add in arbitrary sets of functionality but I wanted to get the …
> Adding in diff plugin execution

- .gitignore
- PATHS.md
- README.md
- examples/charts/paths-example/.helmignore
- examples/charts/paths-example/Chart.yaml
- examples/charts/paths-example/templates/_helpers.tpl
- examples/charts/paths-example/templates/deployment.yaml
- examples/charts/paths-example/templates/service.yaml
- examples/charts/paths-example/values.yaml
- examples/deployments/dev/charts.yaml
- examples/deployments/local/charts.yaml
- examples/deployments/local/values.yaml
- examples/deployments/prod/charts.yaml
- examples/deployments/published/charts.yaml
- examples/values/dev/paths-example/values.yaml
- examples/values/prod/paths-example/values.yaml
- examples/values/replica-values.yaml
- helmexec/exec.go
- state/state.go
Fixes #13 (however is dependent on #12 being merged)
This aims to improve on relative, absolute and <repo>/<chart>
resolution for several of Helmfile manifest attributes as well as
command line arguments.
- Users may now utilize the `-f <filepath>` flag to reference
a helmfile manifest outside of their PWD and have relative paths
in the the `charts[*].values` and `charts[*].chart` attribute resolve
relative to the manfiest's location properly
- Values provided in the `--values` argument are no longer automatically
assumed as relative path references from PWD but instead are
conditionally joined with the PWD if it is determined they are relative
file paths
- Users may still signify a chart in the `.charts[*].chart` attribute
as they do now by having an explicit `<repo>/<chart>` value
> Relative path resolution changes

- README.md
- state/state.go
Thanks a lot for sharing this tool - it really helps out in my workflow!
For my use-case I had to make some adjustments though.
I need to use environment variables inside the paths of the `--values` section.
Also I need to interpolate env vars with `--set` strings. Currently we have the `env` section to use env vars, but it cannot be used for interpolation. 
My use-case is like that:
```
---
charts:
- name: proxy
namespace: default
chart: ./helm/charts/PlatformProxy
values:
- ./helm/values/${PLATFORM_ENV}/${PLATFORM_ID}/config.yaml
- ./helm/values/${PLATFORM_ENV}/${PLATFORM_ID}/secrets.yaml
set:
- name: proxy.base_url
value: "${PLATFORM_ID}.my-domain.com"
```
This PR adds the functionality. In order to render the environment variables reliable, they **MUST** be surrounded by `${}`. An …
> Allow env var interpolation in `set` and `values`

- README.md
- main.go
- state/state.go
I would like to have the ability to set the kubernetes cluster context in the charts.yaml.
This means that upgrade pipelines and users can just use "helmfile sync" and will work correctly across multiple cluster contexts.
> Added ability to set context in charts.yaml

- circle.yml
- main.go
- state/state.go
Have added a new argument `--max-connections` that can be used to set a
limit on the number of concurrent calls to helm at one time. To enable
this I have switched `SyncCharts` from using a WaitGroup to using a pool
of workers and a queue of jobs. No changes have been made to the logic
that performs the sync, however that might be something to look at in
the future.
Fixes https://github.com/roboll/helmfile/issues/23
> Add option to limit concurrent helm calls

- helmexec/exec.go
So that we can just reuse release names after `helmfile delete`.
This is verified to work by confirming that `helmfile delete` does add `--purge` flag to `helm delete`:
```
$ helmfile delete
exec: helm delete --purge brigade-project
release "brigade-project" deleted
```
And by confirming that I can now re-install releases from the same charts.yaml without any modification of release names:
```
PROJECT=deis/empty-testbed ENV=staging IMAGE=mumoshu/golang-k8s-aws:1.9.1 COMMAND='go' SERVICE_ACCOUNT=default helmfile sync
Release "brigade-project" does not exist. Installing it now.
NAME:   brigade-project
LAST DEPLOYED: Tue Feb 27 15:59:38 2018
NAMESPACE: kube-system
STATUS: DEPLOYED
RESOURCES:
*snip*
```
Fixes #33
> Purge releases on deletion

- main.go
- state/state.go
Omit `namespace` in `charts[].namespace` of charts.yaml and then run `helmfile sync -n yourns` to install your charts into `yourns`.
Resolves #31
> Allow specifying a default namespace used across all the releases

- README.md
- examples/deployments/published/charts.yaml
- helmexec/exec.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
In a backward compatible manner, so that (I believe) we could move the discussion made in #25 forward.
Possibly fixes #25
> Fix terminology

- state/state.go
- state/state_test.go
Since [#39](https://github.com/roboll/helmfile/pull/39) the namespace specified in the spec wasn't working anymore.
Helm used the default namespace if -n wasn't set.
> [state] - Fix issue where spec[].Namespace were ignored

- state/state.go
Addresses: https://github.com/roboll/helmfile/issues/45
To test:
Create helmfile.yaml
```
repositories:
- name: monocular
url: https://kubernetes-helm.github.io/monocular
- name: incubator
url: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: fabric8
url: https://fabric8.io/helm
```
Steps to test:
```
export HELM_HOME=`pwd`/.helm
helm init --client-only
helm repo list                                        #no extra repositories
helmfile repos
helm repo list                                        #all three repositories haven't been added (usually one, sometimes two)
```
Failing test
```
ubuntu@kub-master:~/test-helmfile-multi-repo$ export HELM_HOME=`pwd`/.helm
ubuntu@kub-master:~/test-helmfile-multi-repo$ helm init --client-only
Creating …
```
> Synchronous add repository calls avoid helm add repo race conditions

- README.md
- helmexec/exec.go
- helmexec/helmexec.go
- state/state.go
The "helm repo add" command already supports the cert-file and key-file values, so we just have to pass them through. Everything works the same if you don't provide values for them. This is important for deployments where the chart repo is protected by client cert validation.
> Support client certs when accessing remote repos

- .gitignore
- README.md
- main.go
- state/release_filters.go
- state/state.go
- state/state_test.go
Similar to what's described in https://github.com/roboll/helmfile/issues/8
Globbing isn't useful for my particular workflow but I do have a large helmfile where its useful to run just one or two charts out of the entire file.
> Allow running helm against a subsets of charts in a file

- main.go
The option exists for some of the other commands, and I'd like to pass options to `helm upgrade` like `--wait` and `--reset-values`
> Add --args option to sync command

- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- helmexec/runner.go
- main.go
I was looking at the code and noticed the lack of unit tests for the `helmexec` package, so I decided to add a basic first version, bringing statement coverage to 83.7%. There's still a lot of test cases missing (like empty or nil arguments), but they would have required actual code changes to support the edge cases. I wanted to just describe existing, happy-path functionality first.
Writing the tests required me to factor out the actual command-line execution bit into the `Runner`.
Beware, I'm a go beginner. I'd appreciate a critical look at this, especially the package-local functions in the interface in `helmexec.go`. Go crazy with critique :P
> describing current functionality of helmexec as tests

- state/state.go
- state/state_test.go
> render environment variables in repository URLs

- main.go
As discussed in #26, the previous PR #77 prevent applying some args like `"--wait"` for the sync command.
The purpose of this PR is to apply args flag only to sync command and not `UpdateDeps`
> Sync command: change the way we apply args

- README.md
Add environment variable interpolation examples to readme file. See #88, #86, #80, #78, #36.
> Add explanation for envvar interpolation and examples to readme

- README.md
Fix readme file. Envvar interpolation is not working without quotes. See #88.
> Add quotes to envvar example in readme

- main.go
- state/state.go
This fixes the race condition mentioned in #94. I tried to implement it similar to DiffReleases, but used wait groups instead of the done channel. Also I added the same concurrency option that DiffReleases uses. Default is as much workers as releases, same as in DiffReleases.
> Fix race condition. Add concurrency option similiar to DiffReleases

- state/state.go
`path.Dir()` does not support Windows-style directory separators (backslashes). 
This caused invocations such as `helmfile -f subdir\helmfile.yml` to fail. 
Fixed by using `filepath.Dir()` instead.
> Fix resolving relative paths on windows

- .circleci/config.yml
- Dockerfile
- Makefile
* use golang 1.10.1 images everywhere
* introduce a `static-linux` target to build a statically linked 64-bit binary only for the docker image
* use a multi-stage dockerfile for a consistent build environment
This resolves #123.
> build consistent statically linked binary for docker image

- test/integration/run.sh
I am not sure why #103 happens, but I suspect it might be a rare occasion of the pod reporting healthy but the virtual network or service discovery has not fully been initialized. This PR retries the `curl` call to the service to minimize this risk. It's more of a prophylactic measure "into the dark", but it might help.
> retry curl to reduce risk of race condition

- README.md
- state/state.go
- state/state_test.go
The `required_env` function allows you to declare a particular environment variable as required for template rendering.
If the environment variable is unset or empty, the template rendering will fail with an error message.
Example:
```yaml
releases:
- name: {{ required_env "NAME" }}-vault
namespace: {{ required_env "NAME" }}
chart: roboll/vault-secret-manager
set:
- name: proxy.domain
value: {{ required_env "PLATFORM_ID" }}.my-domain.com
```
> Introduce template function `required_env`

- state/state.go
- state/state_test.go
Calling `helmfile charts` with a `helmfile.yaml` like this:
```yaml
releases:
- name: myrelease
chart: somechart
set:
- name: someList
value: 'a,b,c'
- name: otherList
value: '1,2,3'
```
leads to a `helm` invocation like this:
helm upgrade --install myrelease somechart --set someList=a,b,c,otherList=1,2,3
The commas in the values break the comma separation of `--set` values.
This Pull Request fixes the issue by performing escaping:
helm upgrade --install myrelease somechart --set someList=a\,b\,c,otherList=1\,2\,3
> Escape names and values before passing to Helm

- README.md
- state/state.go
This pull request allows the feature #40, that is, `values` accepts the following types:
- A string for values file path.
- A `key: value` map for inline values.
I have tested this feature with the following YAML:
```yaml
releases:
- name: nginx-ingress
namespace: kube-system
chart: stable/nginx-ingress
values:
- another.yaml
- foo:
bar: {{ env "FOO_BAR" }}
```
and result is:
```
% FOO_BAR=1 ./helmfile -f fixture/helmfile.yaml diff
exec: helm diff nginx-ingress stable/nginx-ingress --values /...snip.../another.yaml --values /var/folders/26/mzllyxzd199ggjmq0lvp0bkr0000gn/T/values395419091
...
% cat /var/folders/26/mzllyxzd199ggjmq0lvp0bkr0000gn/T/values161641152
foo:
bar: 1
```
Please let me know if you have any suggestions.
> Inline values support

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
`helmfile delete` has been implying `--purge` but it is not the case since this change.
The new behavior is:
- `helmfile delete` to delete releases, but without purging them
- `helmfile delete --purge` to actually purge releases.
Resolves #71
> Make purge optional when running "helmfile delete"

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
Ref: https://github.com/roboll/helmfile/issues/144
**Feature**
An additional sub-command to the helmfile binary; helmfile test
**Why**
Helm provides helm test (https://github.com/kubernetes/helm/blob/master/docs/chart_tests.md) as a method to run automated tests post chart install to ensure things are working as they should be.
It would be nice to be able to run something like helmfile test against a particular helmfile in order to run helm tests against all charts/releases defined in the file. Either as part of the sync (i.e. helmfile sync --test) to be ran immediately after the corresponding chart is installed, or as a separate command ran after a sync (i.e. helmfile test).
A chart without tests will exit with a 0 status, so it can be safely ran against any charts.
**Notes**
`--cleanup` …
> Add helmfile test sub-command

- Dockerfile
Just bumps to the latest available.
> Docker image uses Helm v2.9.1 (from v2.8.2)

- Dockerfile
Enables the `helmfile diff` command
- git and bash are required to install helm-diff
Note: When installing, helm-diff prints `type: curl: not found` errors, but this is just noisy detection of curl and wget to determine which to use.
> Dockerfile installs helm-diff

- state/state.go
- state/state_test.go
I just encountered #164 as well. This PR should fix that behaviour and fail with an error when there is no release matching the specified selector:
helmfile --selector name=httbin diff
2018/06/12 14:05:48 Specified selector(s) did not match any releases.
> fail when no releases match selector

- main.go
> Ordered helmfile(s) from a directory

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
Our use case is to have a list of helmfile releases version controlled together with all settings and have a CI pipeline that will lint all releases with settings before running sync. The new functionality was mostly copy pasted from the Diff implementation with some extra handling for fetching remote charts so open for any feedback.
> Add helmfile lint support

- main.go
- state/state.go
This is regarding issue #114. This PR allows for args to be set in helmfile. Added section helm which 
args can be set ,as well as context will be set and other contributed key values later on when contributed.
> adding args to be added in helmfile along with context to be set in helmspec

- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- state/state_test.go
Helm may not be version compatible, how about option to overwrite command for switching other version client?
incompatible versions error sample is followings
```
Error: UPGRADE FAILED: incompatible versions client[v2.9.1] server[v2.8.2]
```
> Add the option to specify an alternative helm binary

- main.go
> fix: `helmfile sync` doesn't recognize the default `helmfile.d/` directory

- main.go
- state/state.go
Adds the `--detailed-exitcode` to the `helmfile diff` command to return `1` on failure, and `2` when no error but diff is seen.
This feature requires the latest `helm-diff` containing https://github.com/databus23/helm-diff/pull/78, and `helm` containing https://github.com/helm/helm/pull/4367.
This is verified to work by manually running commands like the followings:
```bash
./helmfile --helm-binary helm211dev -f ./examples/helmfile.d diff --detailed-exitcode; echo $?
./helmfile --helm-binary helm211dev -f ./examples/helmfile.d diff; echo $?
```
Note that, in above example commands, `helm211dev` is a custom `helm` binary that is built from helm's master branch containing [the necessary enhancement to allow propagate non-zero plugin exit code](https://github.com/helm/helm/pull/4367).
> feat: Optional detailed exitcodes for `helmfile diff`

- README.md
* Add a link to github repo dedicated to [our](https://github.com/cloudposse) distribution of helmfiles under the `## Examples` section.
Currently, we have implemented helmfiles for the following:
* kube2iam
* kiam	
* external-dns
* kube-lego
* cert-manager	
* chartmuseum
* nginx-ingress.yaml
* prometheus-operator
* kube-prometheus
* grafana
* datalog
* fluentd-datadog-logs
* fluentd-elasticsearch-logs
* heapster
* dashboard
* portal
* kibana
When we started out, there weren't many examples of how to write helmfiles. Now we're adding more everyweek. We believe there's an opportunity for helmfiles users to collaborate on writing more/better helmfiles to make it even easier to deploy helm charts. 
Ours aren't perfect, we do accept Pull Requests! =) 
Also, we distribute all helmfiles as a …
> Add link to more examples

- README.md
The name is `requiredEnv` and I cannot find any references to `required_env` in the repository anywhere.
> Typofix: required_env -> requiredEnv

- state/state.go
Tested manually by running `helmfile diff` with debug logging:
```yaml
helmDefaults:
tillerNamespace: foo
charts:
- name: grafana
namespace: grafana
chart: stable/grafana
```
```console
$ ./helmfile --log-level debug diff
Comparing grafana stable/grafana
exec: helm diff upgrade --allow-unreleased grafana stable/grafana --namespace grafana --tiller-namespace=foo
```
Resolves #179
> feat(diff): Pass namespace to helm-diff

- state/state.go
- state/state_test.go
Fixes #200
Depends on #216 because this feature requires zap.SuggeredLogger to be passed to HelmState, which is done as part of #200
> fix: Make logging on unmatched selectors less verbose

- README.md
- state/state.go
To instruct `helm upgrade` to wait for resources via `--wait`
Resolves #65
> feat: `wait: true` in each release

- main.go
- main_test.go
- state/state.go
- state/state_test.go
This is a follow-up for #218, fixes the unintentional degradation that broken the use-case described in https://github.com/roboll/helmfile/issues/193#issuecomment-415434408
> fix: helmfile should fail on duplicate release name after filtered by labels

- main.go
- state/state.go
fixes - https://github.com/roboll/helmfile/issues/233
Output on values render error
```
err: failed to render [/Users/sstarcher/xxx/xxx/values.yaml], because of template: stringTemplate:10:18: executing "stringTemplate" at <requiredEnv "HELM_AC...>: error calling requiredEnv: required env var `HELM_ACCOUNT` is not set
```
Also removes panic and sets the output as `apps.Run()` can and will return errors.  Panic makes no sense.
> improve error handling for value rendering

- main.go
This is a follow-up for #235.
We setup the default logger only after the flags are parsed successfully.
That's because we init the logger according to the --log-level flag value.
> fix: panic on flag parsing error

- helmexec/exec.go
- main.go
- state/state.go
- state/state_test.go
- tmpl/file.go
- valuesfile/valuesfile.go
- valuesfile/valuesfile_test.go
`helmfile lint` works with relative chart reference (#252)
The tempalte function `readFile` accepts the path relative to helmfile.yaml
Resolves #246
Fixes #252
> feat: All the paths are relative to helmfile.yaml

- helmexec/exec.go
- tmpl/context.go
- tmpl/file.go
- tmpl/funcs.go
Fixes for the bugs that are introduced by #261, that is values.yaml files specified in `values:` have redundant base path in their prefixes, and remaining .dec files after secrets decryption(https://github.com/roboll/helmfile/issues/251#issuecomment-417285854)
> fix: follow up for the relative paths improvement

- Dockerfile
The Helm client 2.10.0 is incompatible with Tiller 2.9.x, so it may not be desirable to merge this right now. Not sure how eagerly this should be bumped.
> Bump Helm 2.9.1 -> 2.10.0

- README.md
- main.go
- state/state.go
> feat: `helmfiles: <ordered glob patterns of helmfiles>` configuration

- Gopkg.lock
- Gopkg.toml
- README.md
- environment/environment.go
- main.go
- main_test.go
- state/create.go
- state/create_test.go
- state/environment.go
- state/state.go
- state/state_test.go
- tmpl/file.go
- tmpl/tmpl.go
- tmpl/tmpl_test.go
- valuesfile/valuesfile.go
- valuesfile/valuesfile_test.go
> feat: Environment and Environment Values

- args/args.go
> fix: `--args "--set foo=bar"` always result in "unknown flag: --set foo" error

- README.md
- tmpl/funcs.go
> feat: Ability to call arbitrary command from a template

- main.go
- state/state.go
Hey 
This PR addresses https://github.com/roboll/helmfile/issues/288
NOTE:  There are some breaking changes here, in that both `lint` and `template` no longer accept `--concurrency` as an argument.
As both of these commands are almost instantaneous, and local only run it was adding complexity to the code base with little value.  Now they've converged I was able to share the code to untar the dependencies between those two functions.
> Fix set in template and lint

- README.md
Took some time before I realised that I was reading a very old version of the documentation since I followed a link from the README which I thought was to the latest version 🙂 I have updated it.
> docs: update link to documentation for latest released version

- main.go
- state/state.go
This allows calls from an unrelated directory:
```
cd
helmfile -f ~/project/helmfile.yaml
```
Fixes #306
> ensure helmfiles are searched relative to base helmfile

- main.go
I created helmfile.yaml below and executed `helmfile diff` with `--environment` flag. However, it seems that the environment name didn't pass to yamlBuf correctly when reading helmfile.yaml.
```bash
$ cat helmfile.yaml
environments:
production:
staging:
releases:
- name: kiam
chart: stable/kiam
version: 1.2.0
values:
- values/kiam/{{ .Environment.Name }}/values.yaml
secrets:
- secrets/kiam/{{ .Environment.Name }}/secrets.yaml
wait: true
$ tree ./
./
├── README.md
├── helmfile.yaml
├── secrets
│   └── kiam
│       ├── production
│       │   └── secrets.yaml
│       └── staging
│           └── secrets.yaml
└── values
└── kiam
├── production
│   └── values.yaml
└── staging
└── values.yaml
```
```bash
$ helmfile --environment staging --log-level debug diff
Processing helmfile.yaml
err: …
```
> fix: {{ .Environment.Name }} being always blank in helmfile.yaml

- README.md
- main.go
- main_test.go
- state/create.go
- state/create_test.go
- state/state.go
- tmpl/context.go
- tmpl/file.go
- tmpl/funcs.go
- tmpl/tmpl.go
This allows using the values defined in the environments: section.
This is done by using a buffer instead of re-reading the file twice.
see #254
@mumoshu can you weigh in on the approach ?
> double render the helmfile

- README.md
- main.go
- main_test.go
- test/integration/run.sh
- tmpl/file.go
- valuesfile/valuesfile.go
Resolves #326.
**Comments**
This is my first Go, so let me know if there are any obvious rookie mistakes you'd like fixed. Also, let me know if you'd like to see any additional automated testing.
Note that I did *not* implement plumbing the namespace into *values* file templating, so please let me know if you think that should be part of this.
**Testing done**
Beyond running automated tests, I also put together a test `helmfile.yaml` containing `{{ .Namespace }}` and manually ran `helmfile sync` on it. I confirmed that:
1. When `--namespace` is provided, it gets plumbed through as the value for `{{ .Namespace }}`.
2. When `--namespace` is omitted, `{{ .Namespace }}` is an empty string.
> Use --namespace value within Helmfile template

- README.md
- event/bus.go
- event/bus_test.go
- helmexec/runner.go
- main.go
- state/state.go
- tmpl/text.go
Resolves #295
Resolves #330
Resolves #329 (Supports templating of only `releases[].hooks[].command` and `args` right now
Resolves #324
> feat: `prepare` and `cleanup` release event hooks

- main.go
- state/state.go
And fixed the bug that "diff" was not triggering "prepare" hooks.
Ref #363
> fix(hook): event hooks should run on remote charts, too

- main.go
- state/state.go
Prevents helmfile from consuming unnecessarily much time in running `helm
repo update` over and over.
helmfile now marks which repository was updated, and skip second and
further `helm repo update` when all the `repositories` found in a
helmfile.yaml was marked as already updated.
Let's say you had two helmfiles, the first one with repositories `foo` and
`bar`, an the second one with only `bar`. `helmfile repos` will run `helm
update repo` for the first helmfile, marking `foo` and `bar` as already
updated. The second helmfile.yaml contains only `bar`, which is marked as
already updated. So helmfile won't run `helm repo update` for the second.
This applies to all the helmfile command that results in `helm repo
update`, like `repos`, `sync`, `diff` and so on.
Resolves #335
Depends on #353. …
> feat: least frequent repository update

- main.go
Perhaps in latest commits I unexpectedly changed it to require double Ctrl-C to actually interrupt. This fixes it so that one Ctrl-C exists helmfile.
On the way to the fix, I changed the exit-code to 128 + SIGNAL(2 for SIGINT, 15 for SIGTERM) according to common *nix commands.
> One Ctrl-C should exit helmfile gracefully

- README.md
- test/integration/run.sh
The integration test was failing due to that it was still using `--auto-approve` flag which was removed. The documentation was still refering to `--auto-approve` and had no explanation about the new `--interactive` flag. This fixes all these issues.
This a follow up for #368
See https://github.com/roboll/helmfile/pull/374#issuecomment-425291468 for more context.
> fix(ci,doc): follow up for default non-interactivity of helmfile

- .circleci/config.yml
- app_test.go
In go 1.11, the code formatter seems to have changed its formatting rule a bit, that resulted in `make fmt` producing changes introduced in this commit/pr.
> bump go to 1.11

- Dockerfile
Would it be possible to upgrade helm to v2.11.0?
Helm v2.11.0 fixes an issue introduced in v2.10.0 related to corporate proxies, see: https://github.com/helm/helm/issues/4326
> Bump helm to v2.11.0

- main.go
- state/create.go
- state/state.go
- state/state_test.go
Fixes #383. Deprecated `context` directive in favor of `helmDefaults.kubeContext`.
Also fixed `--kube-context` helmfile argument usage
> Deprecated `context` directive

- state/state.go
Suggested fix to remove extra path name after downloading chart from repository.
Closes https://github.com/roboll/helmfile/issues/407
> Remove extra appending of chartName for lint and template

- app_test.go
- state/state.go
Remove duplicated declaration path for cleaner helmfile, for example, this configuration.
```
- chart: projectABC
name: {{ .Environment.Name }}-projectABC
namespace: abc
version: {{ .Environment.Values.projectABC.chart.version }}
valuePath: ../values/{{ .Environment.Name }}/
values:
- common.yaml
- project-abc.yaml
- platform.yaml
- ...
secrets:
- secrets.yaml
```
> add common value path

- README.md
It's possible to install Helmfile via https://formulae.brew.sh/formula/helmfile
> adds Homebrew as an installation method

- main.go
- state/state.go
fixes https://github.com/roboll/helmfile/issues/412
the `apply` command first runs the `diff` command, which triggers the execution of the `cleanup` hooks at the end of the `diff`.
> fix: cleanup hook executed too early for apply command

- CONTRIBUTING.md
- README.md
Add a contribution guide instead and note about the `go get` way there according to the discussion made in the relevant issue.
Resolves #393
> docs: Remove `go get` from the recommended installation methods

- main.go
There was a regression introduced by #439 that broke the first-pass rendering completely. This fixes that.
> fix: first-pass rendering of helmfile.yaml

- main.go
- state/state.go
- state/state_run.go
- state/state_test.go
`helmfile test --concurency N` to set a concurrency number.
It is automatically ceiled at the number of releases just to reduce wasting computing resources.
Also, I've refactored the scatter-gather logic scattered across the code-base.
Resolves #433
> feat: configurable concurrency for `helmfile test`

- README.md
* fix of URL for helmfiles examples in README.md
* Cloudposse repo renamed folder used in URL
> helmfiles examples link URL fix

- cmd/cmd.go
- cmd/deps.go
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/constants.go
- pkg/app/context.go
- pkg/app/errors.go
- pkg/app/two_pass_renderer.go
- pkg/app/two_pass_renderer_test.go
- state/state.go
- state/state_test.go
- test/integration/run.sh
helmfile now runs repository updates and dependency builds by default, but dependency updates.
- `helmfile diff --sync-repos` has been removed and `helmfile diff` updates repository by default. Provide `--skip-deps` to opt-out.
- `helmfile apply --skip-repo-update` has been deprecated. Use `--skip-deps` instead.
- Use `helmfile deps` to update deps rather than just building them.
- Provide `--skip-deps` to skip updating repos and builds deps in sync/diff/apply/template.
Resolves #415 #450
> feat: Opt-out dep-builds and repo-updates

- Makefile
- state/state.go
> fix: remote file provided to `set.file` should not break helmfile

- tmpl/context_funcs.go
- tmpl/context_funcs_test.go
When passing absolute path `/path/to/file`, it converts to `path/to/file` of the relative path and the reading failed.
> fix: read absolute path with readFile

- helmexec/exec.go
> fix: `helmfile sync` should NOT continue when secret decryption fails

- .circleci/config.yml
- Dockerfile
- README.md
- state/state.go
- state/state_test.go
- Adds support for `atomic` in `helmDefaults` or in Helmfile `releases` to enable `--atomic` flag on Helm upgrade/apply
- Bumps Helm to 2.13, a minimum required version for this change (I could not see any implementation of feature toggles based on Helm client versions, so this would just increase minimum Helm requirements)
I've kept the logic the same as existing options, however it doesn't make sense to me that setting an option explicitly to `false` in a release will not override if the equivalent in `helmDefault` is set to `true`. In my mind `helmDefault` should be the default value, but a provided option in the release should take precedence
Ref https://github.com/roboll/helmfile/issues/487
> Support --atomic as a first class directive in helmfile

- state/state.go
- state/state_test.go
Options specified in releases (e.g. `recreatePods`) should override the respective options set in `helmDefaults`. Currently, `helmDefaults` takes precedence.
In the below example, `--force` should not be passed as an additional deployment argument:
```
helmDefaults:
force: true
releases:
- name: example
namespace: example
chart: some/repo
version: ~1.24.1
force: false
```
Fixes https://github.com/roboll/helmfile/issues/492
> Fix: Release options should override helm defaults

- README.md
in the readme the documentation mention a relative path to helm chart and I believe it is a relative path to the current helmfile.
> doc(readme): changed from chart to helmfile

- helmexec/exec.go
- helmexec/helmexec.go
- state/state.go
- state/state_test.go
This removes `release: "your_release_name" not found` errors seen for releases with `installed: false` when running `helmfile sync` and `helmfile apply`.
The problem was that helmfile had been running `helm status` to detect releases to be deleted. helmfile now use `helm list ^YOUR_RELEASE_NAME$` to detect if the release is currently installed or not, which emits no error-like logs on against uninstalled releases.
Fixes #507
> fix: prevent confusing error messages when `installed: false`

- state/state.go
- test/integration/run.sh
> fix: `helmfile delete` should not stop on uninstalled release(s)

- tmpl/context_tmpl_test.go
- tmpl/get_or_nil.go
- tmpl/get_or_nil_test.go
`get` is now able to take one more optional argument, that is used as the default value when the value for the key does not exist.
Resolves #465
Fixes #427
Fixes #357
Ref #460
> feat: Enhanced `get` template function

- README.md
- docs/shared-configuration-across-teams.md
- pkg/app/app.go
This basically allows to define both `releases` and `helmfiles` within a helmfile.yaml, so that you can start using sub-helmfiles easily, by extracting only reused releases.
Resolves #445
> feat: easier way to share configuration across helmfiles

- state/release.go
- state/state.go
- state/state_test.go
Fixes #503 once again. A follow-up to #520 which was incomplete.
> fix: `helmfile diff` should not leave temp values files

- README.md
- main.go
- state/state.go
- state/state_test.go
This adds `helmfile destroy` that is basically `helmfile delete --purge`.
I've also tweaked the behavior of `delete` and `destroy` for releases with `installed: false`, so that it becomes consistent with other helmfile commands.
It now delete releases only when `installed: true` AND the release is already installed.
**Why an another command?**
Because it's easy to remember, and it also makes it easier to iterate on your helmfile.
We've been using `helmfile delete` from the beginning of helmfile,
and several months have been passed since we've added `--purge` to it.
We noticed that we always prefer to use `--purge` so that we can quickly iterate on helmfile by
e.g. `helmfile delete --purge && helmfile sync`. But making `--purge` default makes the `delete` command inconsistent with the …
> feat: `helmfile destroy` deletes and purges releases

- helmexec/exec.go
- helmexec/helmexec.go
- state/state.go
- state/state_test.go
Actually, 4 helm commands including "list", "diff", "status" and "delete" were not taking tiller-rerelated flags into account when called by helmfile. This fixes all these commands.
Fixes #534
> fix: `helmfile destroy` should  delete releases in the specified tiller namespace

- Makefile
- README.md
- event/bus.go
- event/bus_test.go
- helmexec/context.go
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- helmexec/runner.go
- state/create.go
- state/state.go
- state/state_run.go
- state/state_test.go
Partial implementation of #449
> Simple implementation of the tillerless mode

- state/state.go
Since #526, `helmfile apply` have been really able to detect deletion of the last release only, and `sync` has been unable to mark releases with `installed: false` for removal.
Fixes #554
> fix: helmfile apply and sync should properly delete releases

- state/create.go
Since tillerless support we unintentionally broke this, and there isn't a real fix to this.
We must accept a limitation that helmfile needs a tiller installed on your cluster just for decrypting environment secrets.
Fixes #550
> fix:  with environment secrets

- state/state.go
- state/state_test.go
as @mumoshu suggested I have renamed the AffectedReleases.Error field to AffectedReleases.Failed to be more homogeneous with the other fields and to avoir conflits with other Error references.
> fix(struct): renamed Error struct field into Failed

- README.md
- cmd/cmd.go
- go.mod
- go.sum
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/constants.go
- pkg/app/constants_test.go
- state/create_test.go
- state/state.go
- state/state_test.go
Fixes #344 by allowing explicit selectors to be specified for composed helmfiles using the following structure
```
helmfiles:
- helmfile.d/a*.yaml:
selectors:
- name=prometheus      
- name!=zipkin      
- helmfile.d/b*.yaml
- helmfile.d/c*.yaml:
selectors: {}
```
2 modes here : 
* legacy mode when no the env var EXPERIMENTAL is not set to true
* no selector : inherit from the command line.
* selector:  is specified then it is used (an emty means no inheritance from command line and take everything).
* experimental when the env var EXPERIMENTAL=true
* no selector : nothing is inherited from the command line so use all releases.
* selector:  is specified then it is used (an emty means no inheritance from command line and take everything).
> feat(#344): add sub helmfiles explicit selectors

- README.md
- pkg/app/app.go
- pkg/app/app_test.go
- state/create_test.go
- state/state.go
following @mumoshu  comments here https://github.com/roboll/helmfile/pull/567, I removed the usage of subhelmfile path as map key.
I also introduced the *selectorsInherited* key for explicit parent selector inheritance.
> removes dictionary key for subhelm and uses selectorsInherited

- README.md
- state/state.go
See discussion at #552 and #579 
This will add a new event `presync` for releases that have pending changes before they are applied.
Unlike `prepare` and `cleanup` event hooks, this will only be fired for actions and releases that will mutate the chart state in remote cluster.
> Add presync event hook

- helmexec/exec.go
- helmexec/runner.go
- main.go
- pkg/app/app.go
And only useful outputs from helm commands like ones from `helm template` to STDOUT.
Fixes #551
> fix: Send log messages to STDERR

- cmd/cmd.go
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/exit_error.go
- helmexec/runner.go
- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/constants_test.go
- state/release_error.go
- state/state.go
This improves the U/X of `helmfile apply`, by allowing you to selectively apply sub-helmfiles.
When you have two or more sub-helmfiles processed, typing `n` to cancel the first doesn't automatically stop the whole helmfile execution.
Instead, it proceeds by diffing the next sub-helmfile, and asks you to apply it, which should be what the user would expect.
To support this workflow, I have suppressed useless exec logs, correct exit status when diff exists in sub-helmfiles but not in the parent helmfile, and made the final error message emitted by helmfile better.
More concretely, this moves more output from `helm` to STDERR and the `debug` log-level.
The overall output from `helmfile` should be a bit more cleaner especially for `apply`, `sync`, `diff` and perhaps other `helmfile` …
> Various U/X improvements for `helmfile apply`

- docs/writing-helmfile.md
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/constants.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer.go
- pkg/app/two_pass_renderer_test.go
- state/create.go
- state/create_test.go
- state/state.go
The current  [Layering](https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#layering) system didn't work as documented, as it relies on helmfile to template each "part" of your helmfile.yaml THEN merge them one by one.
The reality was that helmfile template all the parts of your helmfile.yaml at once, and then merge those YAML documents. In https://github.com/roboll/helmfile/issues/388#issuecomment-436186278, @sruon was making a GREAT point that we may need to change helmfile to render templates earlier - that is to evaluate a template per each helmfile.yaml part separated by `---`. Sorry I missed my expertise to follow your great idea last year @sruon  😭 
Anyways, this, in combination with the wrong documentation, has made so many people confused. To finally overcome …
> feat: helmfile.yaml layering enhancements

- state/state.go
> fix: log useful error message when failed walking through the file tree

- README.md
- cmd/deps.go
- helmexec/helmexec.go
- main.go
- state/chart_dependency.go
- state/state.go
- state/state_test.go
- test/integration/run.sh
In order to maintain predictable deployments, as developer I want to generate and use "lock files" for all chart versions retrieved from a helmfile.
This change solves it by (1)enhancing `helmfile deps` to generate a lock file containing all the direct chart dependencies of each helmfile state file and
(2)making other helmfile sub-commands reads the lock file and merge the locked version numbers to the helmfile state file being processed.
The lock file is named after the helmfile state file being locked, so that you can have multiple set of the helmfile state file and the lock file pairs in a directory.
When `helmfile deps` are not explicitly run before commands like `sync`, all the helmfile behavior should remain as before.
Let's say you have `helmfile.1.yaml`:
```
repositories:
- name: …
```
> feat: Dependency locking

- README.md
- state/state.go
`postsync` events are triggered after each release is applied to the cluster in `helmfile sync` or `helmfile apply`.
This should be a best hook to notify only after each sync failed or succeeded. This can be used for running operations like patching K8s resources managed by helm, but that should be the last-resort. Maybe you should fork/update the chart, or submit a feature request to add `replicated/ship` integration to `helmfile` in that case :)
Resolves #599
> feat: postsync hooks

- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer_test.go
- state/create.go
- state/create_test.go
- state/testfs.go
This enhances helmfile's internal environment values files loader to expand glob patterns (#606)
Fixes the existing bug that helmfile was unable to load environment values file from absolute path (#549)
Resolves #606
Fixes #549
> feat: expand glob pattern in environment values file path

- cmd/cmd.go
- main.go
- Change exit code from 2 to 3 when helmfiles have no releases that match a selector
- Introduces new flag `--allow-no-matching-release` to exit 0 when no releases match a selector.
See discussion at #597
> feat: ability to exit zero with no releases match selector (Fixes: #597)

- README.md
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer_test.go
- state/create.go
- state/create_test.go
- state/environment.go
- state/state.go
- state/state_test.go
```yaml
environments:
default:
missingFileHandler: Warn
values:
- path/to/values.yaml
secrets:
- path/to/secrets.yaml
```
`missingFileHandler` set to `Warn`, `Info`, or `Debug` results in helmfile NOT stop when `path/to/values.yaml` or `path/to/secrets.yaml` is missing.
Resolves #548
While implementing the above feature, I also found a bug that has been causing #559. This also fixes that.
To verify it is actually fixed, create an example helmfile.yaml that looks like the below, and run `helmfile diff`:
```
$ cat helmfile.yaml
environments:
default:
secrets:
- env-secrets.yaml
releases:
- name: myapp
chart: nginx
namespace: default
secrets: [secrets.yaml]    # Notice this file does not exist
values:
- ingress:
enabled: true
$ helmfile diff
could not deduce `environment:` block, configuring …
```
> feat: optionally allow missing environment values/secrets files

- README.md
- cmd/cmd.go
- environment/environment.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer.go
- state/create.go
- state/environment_values_loader.go
- state/state.go
- state/state_test.go
- state/storage.go
Adds the `helmfiles[].environment.values` that accepts a mix of file pathes and inline dicts:
```yaml
helmfiles:
- path: path/to/nested/helmfile.yaml
environment:
values:
- key1: val1
- values.yaml
```
The values files are loaded in the context of the parent state file. For example, in case the above state file is located at `/path/to/helmfile.yaml`,
`values.yaml` is located at `/path/to/values.yaml` instead of `/path/to/nested/values.yaml`.
Resolves #523 
---
I've also included the fix for #615 and the another fix that fixes the regression due to that. I've included all hese 3 commits into this one PR, because all of them correlate to each other(I think).
>  feat: specify env values from the parent to the nested state

- go.mod
- go.sum
Upgrades sprig from 2.15.0 to 2.16.0 to get `values` function support for Dicts. Addresses #630
> feat: upgrade sprig to 2.16.0 for #630

- README.md
- pkg/app/app_test.go
- state/state.go
We added envvals overrides in the state file via #622 two days ago:
```
helmfiles:
- name: sub.helmfile.yaml
environment:
values:
- mykey: myvalue
```
This change removes the `environment` level in the above cofig, so that it looks like:
```
helmfiles:
- name: sub.helmfile.yaml
values:
- mykey: myvalue
``
This is an inevitable breaking change towards #361. But I wanted to break it earlier so that less folks are affected.`
Ref https://github.com/roboll/helmfile/issues/361#issuecomment-497530819
> change the nest level of envvals overrides for nested state files(sub-helmfiles)

- README.md
- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/desired_state_file_loader.go
- pkg/app/load_opts.go
- pkg/maputil/maputil.go
The addition of `--set k1=v1,k2=v2` and `--values file1 --values file2` was originally planned in #361.
But it turned out we already had `--values` for existing helmfile commands like `sync`. Duplicated flags doesn't work, obviously.
So this actually add `--state-values-set k1=v1,k2=v2` and `--set-values-file file1 --set-values-file file2`.
They are called "state" values according to the discussion we had at #640
Resolves #361
> feat: override state(former "environment") values via command-line args

- go.mod
- pkg/app/app_test.go
- pkg/app/two_pass_renderer.go
- pkg/tmpl/context_tmpl.go
Seems like we are affected by https://github.com/golang/go/issues/24963. That is, even though we internally use the template option `missingkey=zero`, in some cases it still prints `<no value>` instead of zero values, which has been confusing the state yaml parsing.
This fixes the issue by naively replacing all the remaining occurrences of `<no value>` in the rendered text, while printing debug logs to ease debugging in the future when there is unexpected side-effects introduced by this native method.
Fixes #553
> fix: "cannot unmarshal !!str `<no value>` into bool" errors in state templates

- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer.go
- pkg/environment/environment.go
- pkg/maputil/maputil_test.go
- pkg/state/create.go
- pkg/state/environment_values_loader.go
- pkg/state/release.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
This adds `values` to state files as proposed in #640.
```yaml
values:
- key1: val1
- defaults.yaml
environments:
default:
- values:
- environments/default.yaml
production:
- values:
- environments/production.yaml
```
`{{ .Valuese.key1 }}` evaluates to `val1` if and only if it is not overrode via the production or the default env, or command-line args.
Resolves #640
> feat: state values

- pkg/helmexec/exec.go
helm-secrets uses the `HELM_SECRETS_DEC_SUFFIX` env var to define the name of the output file
we should have the same logic in helmfile, to come up with the same filename
It only affects people using the `HELM_SECRETS_DEC_SUFFIX` env var
Use-case: if you want to run multiple `helmfile` commands in parallel, without conflicts. in this case, you need to decrypt secrets with different suffixes.
> fix: use the same logic as helm-secrets when decoding secrets

- pkg/state/state.go
- pkg/state/state_test.go
fixes #665.
There was an issue a the regexp reding the version from helm output.
> fix: fixes a regexp issue for release summary

- pkg/app/app_test.go
- pkg/state/create.go
Prior to this change, the resulting lock file was called `<bases[0]>.lock`, instead of `<filename>.lock`.
This change ensures the final, merged state has the correct `.FilePath`.
Please let me know how I can improve/augment this one-liner. It'd be nice, for example, to have a test that prevents regressions.
> fix: persist original file path when using bases

- pkg/app/app.go
- pkg/remote/remote.go
Extends the remote-helmfile feature to also work when loading the first state file.
This should be useful for people who wants to give helmfile a try without ever opening `$EDITOR`.
> feat: `helmfile -f <go-getter url>`

- pkg/state/release.go
- pkg/state/state_exec_tmpl_test.go
Allows the release version to be a Go template.
Fixes #669
> feat: make release version templatized

- README.md
- pkg/state/helmx.go
- pkg/state/state.go
This enhances helmfile so that it can:
- Treat K8s manifests directories and Kustomize projects as charts
- Add adhoc chart dependencies on sync/diff/template without forking or modifying chart(s) (#649)
- Add adhoc patches(JSON Patch or Strategic Merge Patch supported) to be applied to the K8s resources before sync/diff/template, without forking or modifyin chart(s) (#650)
The usage is as outlined in https://github.com/mumoshu/helm-x/tree/master/examples/helmfile.
Add any or all of `dependencies:`, `jsonPatches:` and `strategicMergePatches:` so that it adds additional flags to `helm` calls that is only supported by `helm x`.
```yaml
releases:
- name: kustomize
chart: ../kustomize
- name: manifests
chart: ../manifests
- name: foo
chart: incubator/raw
dependencies:
- alias: bar
chart: …
```
> feat: experimental integration with helm-x

- README.md
- pkg/argparser/args.go
- pkg/argparser/args_test.go
- pkg/state/create.go
- pkg/state/state.go
- pkg/state/state_test.go
The root cause of this bug was due to that `--kube-context` and `kubeContext` had been treated specifically in code. So on the way I have made it consistent with other per-release settings - by adding `kubeContext` for each release and treating `helmDefaults.kubeContext` as just the default value for per-release setting.
Fixes #674
> fix: helmDefaults.kubeContext ignored in `helm diff` of `helmfile apply`

- pkg/state/state.go
It was just missing the appendConnectionFlags call to compose flags passed to `helm delete` there. This fixes it.
Fixes #605
> fix: `installed: false` not respecting TLS settings and tiller namespace

- README.md
- pkg/event/bus.go
- pkg/event/bus_test.go
Fixes #689 
This adds a new yaml entry for the hook definition to allow the users to specifcy if they want to show the `command` logs or not.
here is an example.
```
releases:
- name: myapp
chart: mychart
hooks:
- events: ["cleanup"]
showlogs: true
command: "kubectl"
args: ["get", "ingress"]
```
this will display the following output:
```
hook[cleanup] logs | NAME              HOSTS                          ADDRESS   PORTS   AGE
hook[cleanup] logs | catalog-gateway   tdc.foo                                  80      2d6h
hook[cleanup] logs | dataset           foobar.barr.foo.xxxxxxx.com              80      2d6h
hook[cleanup] logs | rating            fooba.barr.foo.xxxxxxx.com               80      2d6h
hook[cleanup] logs | sharing           foobar.barr.foo.xxxxxxx.com              80 …
```
> feat(689): optionally show logs for hooks

- pkg/state/envvals_loader.go
This helps a lot when debugging go templates. Especially if you're not so good at go template, like me.. :-)
> feat: When values.yaml.gotmpl can't be parsed as YAML, print the YAML.

- pkg/remote/remote.go
- pkg/remote/remote_test.go
The remote helmfile feature introduced by #648 was unable to be sourced from private git repositories due to URL parsing issue in helmfile. This fixes that.
Ref https://github.com/roboll/helmfile/issues/469#issuecomment-505236600
> fix: remote helmfile from git::ssh source

- pkg/remote/remote.go
> fix: Absolute paths for -f not working on Windows

- main.go
This adds the possibility to use a "=" in the parameters passed to --state-values-set
previous comportment:
`helmfile --state-values-set 'test="abcde==fg",test2="abcde"'` => outputs 'test="abcde",test2="abcde"'
new comportment:
`helmfile --state-values-set 'test="abcde==fg",test2="abcde"'` => outputs 'test="abcde==fg",test2="abcde"'
> fix: enabled '=' in a value for --state-values-set

- go.sum
- pkg/state/state.go
This is a revised version of https://github.com/roboll/helmfile/commit/41e44f74a37ebca0394d9ec4546c27208f8a1adf, which doesn't make CI angry and a more straight-forward(yet smelling) implementation
Fixes #737
> fix: `fatal error: concurrent map read and map write` on concurrency > 1

- pkg/state/helmx.go
- pkg/state/state.go
Use with the helm-x support(#673)
This enhances config syntax to accept adopt: [NS/KIND/RESOURCE_NAME] at the release level so that helmfile calls helm-x to transparently import existing resources at the installation time.
Resolves #84
> feat: Adopt existing K8s resources as Helm release on install

- pkg/tmpl/context_funcs.go
When fromYaml fails, it is sometimes useful to see the offending yaml for debugging purposes. This prints adds the content of the yaml to the error message.
> print yaml content on error in fromYaml

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
Related to #782 and #444 
- Allows concurrent decryption of different secrets files
- Caches decrypted secrets by original file path and returns decrypted results from memory
- Secrets being run through an instance of helmexec will be cached and run as fast as possible concurrently
NB: This particular PR doesn't make _all_ calls to secrets cached and concurrent.  Environment Secrets in particular seem to not be evaluated with a ScatterGather(), and doesn't use the same helmexec instance as other parts of the code, so it doesn't take advantage of these changes.  Some reworking of the plumbing there would be needed.
> Cache secrets and concurrent decryption

- pkg/state/state_run.go
> fix: Base scatterGather() concurrency on items parameter

- Dockerfile
As referenced in issue: https://github.com/roboll/helmfile/issues/789 and https://github.com/roboll/helmfile/issues/792.
For now I've made it contact kubernetes for the latest version every time, looking at the implementation of the helm installation would you prefer for it to be a hardcoded and checksum confirmed version added?
> Add kubectl and jq to Dockerfile

- pkg/app/app.go
- pkg/app/desired_state_file_loader.go
- pkg/state/create.go
- pkg/state/create_test.go
- pkg/state/state.go
Closes #444 and #782 
This is the final PR to fully cache and parallelize helm secret decryption.  It threads the shared helmexec.Interface into the StateCreator and HelmState structs to be used during environment secret decryption.  This should effectively cache secrets for the duration of a helmfile run, regardless of where they are first decrypted.
This is based on the work in #800, so it is draft until that PR is final.
> Shared helmexec for Environment Secrets

- Makefile
- go.mod
- go.sum
- pkg/remote/remote.go
> fix: clean up invalid remote state file cache

- Dockerfile
- Makefile
So that the release process can be (probably) 2x faster
> release: skip downloading go modules in container image builds

- pkg/app/app.go
* `0.60.2` would only update repos once
* 38.92s user 13.14s system 61% cpu 1:24.04 total
* `0.81.3` will update repos for each helmfile
* 93.18s user 14.82s system 119% cpu 1:30.69 total
* `fix` restores old behavior
* 31.90s user 7.35s system 74% cpu 52.700 total
> move context outside to limit duplicate repo updates

- Dockerfile
This adds helm-tiller plugin to published docker image.
Without helm-tiller, having following `helmfile.yaml` (using helmfile as a templating tool):
```
repositories: []
helmDefaults:
tillerNamespace: helm-releases  #dedicated default key for tiller-namespace
tillerless: true #dedicated default key for tillerless
releases:
- name: talk
chart: ../charts/nunl-talk
values:
- releases/talk-values.yaml.gotmpl
environments:
test:
values:
- environments/test/values.yaml
secrets:
- common/secrets.sops.yaml
- environments/test/secrets.sops.yaml
```
And executing `helmfile -e test template`, this results in following error:
```
Decrypting secret /workspace/deploy/helmfile/common/secrets.sops.yaml
Decrypting secret /workspace/deploy/helmfile/environments/test/secrets.sops.yaml
helm exited with …
```
> fix: add helm-tiller plugin to docker image

- pkg/state/chart_dependency.go
- pkg/state/state.go
Ref https://github.com/roboll/helmfile/issues/668#issuecomment-529054165
> fix(cmd/deps): make `helmfile deps` to work w/ helm 3.0.0-beta.3

- pkg/remote/remote.go
Not entirely sure of the consequences of this change, but on first try it works for multiple level dependency helmfiles pulled from git:
Example:
master_helmfile:
```yaml
helmfiles:
- path: git::ssh://git@github.com/firstrepo@helmfile.yaml?ref=master
```
firstrepo@helmfile.yaml:
```yaml
helmfiles:
- path: git::ssh://git@github.com/secondrepo@helmfile.yaml?ref=master
```
secondrepo@helmfile.yaml:
```yaml
releases:
...
```
If this change is not in place, the resulting `helmfile build` for this scenario would copy `secondrepo@helmfile.yaml` into the subdirectory of first repo cache, then helmfile is not able to find secondrepo@helmfile.yaml because it doesn't find it under `.helmfile/cache/first_repo` and doesn't know to look for the file where it placed it under …
> Fix recursion for helmfiles pulled from git

- README.md
- pkg/app/app_test.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/state.go
- pkg/state/state_test.go
This adds support for the `--ca-file` option to the `helm repo add` command via the RepositorySpec. The implementation for this is identical to the implementation for `RepositorySpec.CertFile` and `RepositorySpec.KeyFile`, and adds an example to the README.
While the use-case for this is fairly rare, it's a fairly easy implementation (unless I'm missing something here).
Our helmfile usage is fairly vanilla, but this could be a breaking change if anyone uses helmfile as a Go library. I'm just not familiar enough with the various use-cases to know whether that's a problem, but I think that would be the main concern with this change.
resolves #855
> feat: `helm repo add --ca-file` via repositories definition

- pkg/state/state.go
> fix: invalid duration passed to helm 3 upgrade

- README.md
This adds clarity in docs by:
- Changing references to the supported file extension
- Previously, using `values.tmpl` in helmfile.yaml would throw errors. `values.gotmpl` gives expected output
> Fix: Change use of `tmpl` to `gotmpl` in README

- pkg/state/chart_dependency.go
At the moment, if you have a helmfile.yaml like so:
```
releases:
- name: metrics-server
namespace: kube-system
chart: stable/metrics-server
```
If you try to run `helmfile deps`, you will get a 0 exit code and no log
output at whatsoever, signaling that there weren't any problems, but no
lock file will get created.
For example:
```
root@316073d4a104:/# helmfile deps
root@316073d4a104:/#
```
This behavior doesn't appear to be documented and is unintuitive to the
user.
This change adds a warning output for this same use case:
```
root@316073d4a104:/# helmfile deps
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information.
root@316073d4a104:/#
``` …
> Warn users when no repositories are defined

- docs/writing-helmfile.md
It's a small thing, but I've been bitten hard by duplicate keys in YAML before.
> Update templating example typo

- pkg/event/bus.go
- pkg/event/bus_test.go
- pkg/state/state.go
This resolves #826 by adding a success flag to the event template data for use in hooks. See the related issue for use-cases.
I've made a first pass that is rather crude so please provide feedback if you would like it done a different way. I had some other ideas but I couldn't think of one that felt much cleaner so I've opted for this simplest one at this point.
> feat: Enhance postsync event to include `.Error`

- Dockerfile
In trying to use the base quay.io/roboll/helmfile image to deploy a chart that depended on an external repository, I ran into this error:
```
Adding repo bitnami https://charts.bitnami.com/bitnami
in ./helmfile.yaml: in .helmfiles[0]: in dirac/helmfile.yaml: helm exited with status 1:
Error: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```
The minimum to work around that error would be approximately:
```
mkdir /root/.helm/repository && echo apiVersion: v1 > /root/.helm/repository/repositories.yaml
```
Though there might be other things that I'm unwittingly depending on in the base `helm init`. What do you think?
> Run "helm init --client-only" in Dockerfile

- .circleci/config.yml
- Dockerfile
- go.sum
Upgrade helm to v2.15.1, which is latest release. 
Relates to https://github.com/Homebrew/homebrew-core/pull/45743 (already built with latest helm)
> Helm 2.15.1

- go.mod
- go.sum
The fragment variant of the URIs e.g. `foo: ref+awsssm://path/prefix#key` was not working. This change fixes that by bumping `vals` which is the library providing the SSM support, along with other dependencies.
> Fix SSM integration

- pkg/state/state.go
If we specify ref+ syntax in a values file, run vals against that file. This should work for both `.yaml` and `.yaml.gotmpl` files, since it will evaluate the go-templating before proceeding to the ref evaluation.
I'm not sure the best way to test this. The initial implementation didn't have a test framework for me to leverage. I built locally and tested against my helmfile setup. It appears to work. 
```
releases:
- name: my-app
chart: stable/foo
values:
- values.yaml
- morevalues.yaml.gotmpl
```
```
foo: ref+vault://127.0.0.1:8200/mykv/foo?proto=http#/mykey
bar:
baz: ref+vault://127.0.0.1:8200/mykv/foo?proto=http#/mykey
```
```
boo: ref+vault://127.0.0.1:8200/{{ .Environment.Name }}/foo?proto=http#/{{ .Release.Name }}
```
Signed-off-by: Tom Duffield <tom@chef.io>
> Run vals against values files that contain the syntax

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/state/state_test.go
This overrides the default helm command, if provided, as soon as possible.
This way it is already used in `visitStates`.
I ran into an issue using `HELM3` and `--helm-binary` together with helm-secrets. 
I previously used tillerless, which i could now remove. This however caused `DecryptSecret` to fail, as it would still use the helm2 binary; because it runs before the first `helm.SetHelmBinary` call.
While helm-secrets is not fully helm3 compatible yet, its uses within helmfile are, and i was able to just install it as a helm3 plugin.
> Set HelmBinary in execer constructor

- .circleci/config.yml
- pkg/helmexec/exec.go
- pkg/state/state.go
- test/integration/run.sh
This enhances the integration test suite so that it can be run against not only helmfile + helm v2 but also with helm v3.
Also added two fixes to Helmfile that needed to pass the test.
Finally, from now on the integration test is run against pull requests from forks, so that we can catch more bugs before merging PRs, which helps maintaining this project. I believe it is intended to be so but that didn't work until now due to misconfiguration.
> Make helmfile + helm v3 pass the integration test suite

- .circleci/config.yml
- Dockerfile.helm3
- Makefile
Adds the Dockerfile for Helm v3(Dockerfile.helm3) that contains both Helmfile and Helm v3(currently 3.0.0-rc.2).
Changes the CircleCI workflow to include a job to build the v3 image on every PR. The release job is enhanced to build and push the image with a tag prefixed with `helm3-`. So the resulting image should be available via e.g. `quay.io/roboll/helmfile:helm3-v0.90.5`.
> Build alternative container image for use with Helm v3

- pkg/app/app.go
- pkg/app/run.go
This ports the fix for `helfmile apply` to `delete` and `destroy`, so that specifying `--selector` does not break those commands anymore.
Ref #919
> Port the `needs` fix for `helmfile apply` to `delete` and `destroy`

- pkg/app/app.go
- pkg/app/run.go
This ports the fix for `helfmile apply` to `sync`, so that specifying `--selector` doesn't break `helmfile sync`.
Also make `helmfile template` DAG-aware, so that the manifests are rendered in the order of dependency.
Ref #919
> Port the `needs` fix for `helmfile apply` to `sync`, and make `template` DAG-aware

- pkg/app/app.go
- pkg/state/state.go
- pkg/state/state_run.go
- pkg/state/state_test.go
The recent addition of the DAG support(`needs`) and the fixes on it broke the delete-on-sync functionality. And there were two more bugs. One is that it was not correctly running `helm delete` when needed and the another is that it was failing when `--selector` is specified and the releases to delete by sync found, but nothing actually got deleted. This fixes all of them.
Fixes #941
> fix: release not found on uninstall through sync/apply

- .circleci/config.yml
- Dockerfile.helm3
- pkg/app/app_test.go
- pkg/exectest/helm.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/chart_dependency.go
- pkg/state/state.go
- pkg/state/state_test.go
- test/integration/run.sh
Runs `helm version` in helmexec.New, and exposes a method on Interface to allow other packages to use the detected version. Preserves compatibility with previous HELMFILE_HELM3 mechanism.
Resolves #923
> feat: Automatically enable Helm v3 mode

- pkg/app/app_test.go
- pkg/state/release.go
Right now, one has to use either `valuesTemplate` or `values`. This is unexpected, it would be much more natural to allow using both at the same time. This implements that. The same for `setTemplate` and `set`.
> Allow combining valuesTemplate and values, same for setTemplate

- pkg/app/two_pass_renderer.go
As discussed in #937, change the log level of the message
```
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read iae.yaml.part.0: reading document at index 1: yaml: unknown anchor 'iae' referenced
```
from info to debug.
> Log "could not deduce `environment:` block" message at debug level

- go.mod
- go.sum
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/state/state_test.go
Those are not actually random but would have looked like so. We use an external go pkg `variantdev/vals` to expand urls like `ref+vault://foo/bar` contained in release values into their respective secret values.
There was a bug in `vals` that it tries to expand unintended types of strings which resulted in confusing errors like reported in #973.
`vals` fixed the issue in https://github.com/variantdev/vals/commit/ba4c7a29875ab5fea5df80d7c25b5d6ccdce07c0. This commit upgrades `vals` to accomodate that.
Fixes #973
> Fix random "expansion errors" in large values contained in `values`

- pkg/app/app_test.go
- pkg/state/state_run.go
> Fix regression in the order of processed releases when concurrency is 1

- README.md
- pkg/state/state.go
- pkg/state/state_test.go
This PR adds cleanup-on-fail flag to the release as well as helmDefaults spec.
This allows failed releases to cleanup new resources.
> Adding the cleanup-on-fail flag to upgrade command

- README.md
- pkg/state/state.go
It is how `cleanupOnFail` to be consistent with other keys.
Ref #969
> Fix capitalization of cleanup-on-fail config key

- pkg/app/app_test.go
- pkg/state/create.go
- pkg/state/create_test.go
When helmfile is run with `--environment NAME` and there was a base hemlfile that misses `environments`, helmfile had been trying to load env values for NAME and failing.
A base helmfile is allowed to reference values from within itself, but that's optional. In other words, a base helmfile that misses the env is okay as long as it doesn't self-reference env values.
So, this change allows missing env and env values while loading base helmfile. After loading, a base helmfile can fail due to referencing missing env values, but that's okay.
Fixes #1008
> Do not fail due to missing env in base helmfile

- pkg/helmexec/exec.go
It looks like during the beta phase the testing functionality was tweaked / changed back during the beta phase but has since been returned back to how it worked originally.
RE: https://github.com/helm/helm/commit/a6f4bc1bc0fc721aa501f7b8667928b2ec4f0016
Signed-off-by: Jake Hill <jake@naphta.uk>
> Fix Helm test having run subcommand with helm3

- main.go
- pkg/maputil/maputil.go
- pkg/maputil/maputil_test.go
This pull request adresses https://github.com/roboll/helmfile/issues/899
It adds support for indexed key arguments and escaped dot arguments.
Things like `--state-values-set config\.yml.something=abc` or `--state-values-set config.something[0]=abc` can be passed in the command line.
@mumoshu this should be ready for review.
> Improve --state-values-set parsing

- README.md
- pkg/app/app_test.go
- pkg/state/state.go
resolves #1014
This makes it possible to pass the API Capabilities to helmfile when executing a task that does not render against an actual cluster (diff, template, apply).
The list of api versions are currently passed via `helmDefaults`. Maybe it would also make sense to override in specific `environments`, but this is not implemented.
This is my first contribution to a golang project, any feedback will be appreciated :)
> feat: Option to pass apiVersions to `helm diff` and `helm template`

- README.md
- pkg/app/app_test.go
- pkg/state/state.go
https://github.com/roboll/helmfile/pull/1046 introduced the `apiVersions` configuration option in helmfile.yaml. The api versions were passed via `--api-versions` to `helm template` and `helm diff`. 
However `helm diff` does not implement the `--api-versions` parameter, and does not plan to do so (see https://github.com/databus23/helm-diff/pull/175). Instead, with helm 3.1.0 `helm diff` will render templates against the actual cluster, removing the need to specify api versions manually.
This PR removes passing API versions to `helm diff` (which caused helm diff to fail, if `apiVersions` was specified in helmfile). The API versions are still used when running `helmfile template`, which may make sense for some use cases.
> do not pass --api-versions to "helm diff"

- pkg/state/state.go
When chart is not set, an exception without any hints occure due
normalizeChart tries to access the first character of a 0 length string.
Properly inform user of missing chart instead.
> Fix crash on missing chart

- pkg/state/state.go
This fixes the issue reported in Slack https://sweetops.slack.com/archives/CE5NGCB9Q/p1582088381195000
> fix: `helmfile -n ns status` should set ns for helm 3

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/load_opts.go
`--retain-values-files` prevents temporary values files that were passed to Helm commands run by Helmfile for debugging purpose.
With that, you can manually rerun helm commands that were logged when `--log-level=debug` is enabled.
Resolves ##1117
> feat: `helmfile --log-level=debug apply --retain-values-files`

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
This adds validation for when a helmfile declares a repository URL but not a repository name.
Resolves #1112.
> Added validation for empty repository names

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/state/state.go
This adds ability for helmfile to call helm template --validate introduced in helm 3.
Note: what about helm 2 support? Should we forbid this flag when using helm 2?
Fixes https://github.com/roboll/helmfile/issues/1105
> feat: add helmfile template --validate

- go.mod
- pkg/tmpl/context_funcs.go
> fix: `exec` template func should not throw away stdout when stdin is non empty

- go.mod
- go.sum
For support for the advanced AWS profile usage in retrieving AWS SSM params/secrets https://github.com/variantdev/vals/issues/19
> Bump variantdev/vals to 0.2.0

- pkg/tmpl/context_funcs.go
- pkg/tmpl/context_tmpl.go
Enhances Helmfile to print more helpful message on error while calling `exec` template function.
Helmfile has been printing error messages like the below:
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:5:8: executing "stringTemplate" at <exec "./exectest.sha" (list)>: error calling exec: exit status 1
```
Adding captured stdout and stderr, with some indentation to make it readable, it now produces the following message on missing executable:
```
$ make build && ./helmfile build
go build
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:5:8: executing "stringTemplate" at <exec "./exectest.sha" (list)>: error calling exec: fork/exec ./exectest.sha: no such file or directory
COMMAND:
./exectest.sha
ERROR: …
```
> feat: Better exec error reporting

- pkg/state/envvals_loader.go
Since mergo had been bumped to 0.3.9 in https://github.com/roboll/helmfile/commit/6643a41ea3bb2e8f87a860d562cfdb6b9ca72d1b an environment value like:
```yaml
affinity: {}
```
Was not merged properly (not merged) instead it threw an error
that it cannot find the key "affinity" in the environment values even
though it was outputted in debug output as read in properly.
Error message:
```
err: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:2:23: executing "stringTemplate" at <.Environment.Values.affinity>: map has no entry for key "affinity"
in ./helmfile.yaml: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:2:23: executing …
```
> fix: empty map merge was not working after mergo bump

- pkg/app/desired_state_file_loader.go
Instead of panic, Helmfile will now kindly emit a clear error message like this:
```
releases:
- name: foo
```
```
$ ./helmfile -f helmfile.emptychart.yaml  build
in ./helmfile.emptychart.yaml: error during helmfile.emptychart.yaml.part.0 parsing: encountered empty chart while reading release "foo" at index 0
```
Resolves #999
> feat: Emit clear error message instead of panic on empty chart name

- pkg/app/app.go
- pkg/app/run.go
- pkg/state/release_error.go
- pkg/state/state.go
It's now as simple as:
```
********************
Release was not present in Helm.  Diff will show entire contents as new.
********************
default, mysecret, Secret (v1) has been added:
-
+ # Source: raw/templates/resources.yaml
+ apiVersion: v1
+ kind: Secret
+ metadata:
+   labels:
+     app: raw
+     chart: raw-0.2.3
+     heritage: Helm
+     release: raw
+   name: mysecret
+ stringData:
+   foo: bar
Identified at least on change
```
```
$ echo $?
2
```
Fixes #749
> Fix misleading `helmfile diff` output

- go.sum
- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/run.go
- pkg/state/state.go
- pkg/state/state_test.go
Just like `--suppress-secrets` option of diff and apply command, there is an option `--include-tests` comes from [helm-diff](https://github.com/databus23/helm-diff) plugin.
```diff
NAME:
helmfile diff - diff releases from state file against env (helm diff)
USAGE:
helmfile diff [command options] [arguments...]
OPTIONS:
--args value                  pass args to helm exec
--set value                   additional values to be merged into the command
--values value                additional value files to be merged into the command
--skip-deps helm repo update  skip running helm repo update and `helm dependency build`
--detailed-exitcode           return a non-zero exit code when there are changes
+  --include-tests               enable the diffing of the helm test hooks
--suppress-secrets …
```
> feat: add option `--include-tests` for diff and apply command

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/destroy_test.go
- pkg/app/diff_test.go
- pkg/app/run.go
- pkg/state/state.go
It tries to detect deletions of releases (installed: false). When detected, it will exists with 2, as denoted by `--detailed-exitcode`.
With `detailed-exitcode`, the output should be:
```
$ helmfile diff --detailed-exitcode
Decrypting secret /example/helmfile/envsecrets.yaml
Listing releases matching ^raw$
raw 	default  	1       	2020-04-07 21:03:40.236842 +0900 JST	deployed	raw-0.2.3	0.2.3
Affected releases are:
raw (incubator/raw) DELETED
Identified at least on change
```
```
$ echo $?
2
```
And without `detailed-exitcode`:
```
helmfile diff
Decrypting secret /example/helmfile/envsecrets.yaml
Listing releases matching ^raw$
raw 	default  	1       	2020-04-07 21:03:40.236842 +0900 JST	deployed	raw-0.2.3	0.2.3
Affected releases are:
raw (incubator/raw) DELETED
```
```
$ echo $?
0
``` …
> feat: `helmfile diff --detailed-exitcode` should also detect deletions

- pkg/tmpl/context_funcs.go
- pkg/tmpl/context_funcs_test.go
- pkg/tmpl/context_tmpl_test.go
Resolves #572 
Force error test with this `values.yaml.gotmpl` and without any environment variables `CLUSTER_NAME`  and `DNS_ZONE` has been set
```yaml
dnsZone: {{ required "Either DNS_ZONE or CLUSTER_NAME required" (coalesce (env "DNS_ZONE") (env "CLUSTER_NAME")) }}
```
error message will be shown as:
> in helmfile.yaml: in .helmfiles[23]: in helmfile.yaml: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:2:12: executing "stringTemplate" at <required "Either DNS_ZONE or CLUSTER_NAME required" (coalesce (env "DNS_ZONE") (env "CLUSTER_NAME"))>: error calling required: Either DNS_ZONE or CLUSTER_NAME required
> feat: add tmpl function `required`

- Dockerfile
Put tiller binary on the path in helm v2.X container image so that helm-tiller plugin will use it instead of duplicating the download of helm tarball and performing version check.
> put tiller on path for use in helm-tiller plugin.

- main.go
- pkg/state/state.go
> fix: helmDefaults.timeout and releases[].timeout not working for `helmfile test`

- pkg/app/two_pass_renderer.go
- pkg/environment/environment.go
- pkg/state/state_exec_tmpl.go
This commit proposes a potential solution for
https://github.com/roboll/helmfile/issues/1201
The gist is that, if prestate rendering fails, for any reason,
we do not populate the .Values in the second pass renderer.
I think that what have been expected in this case is to populate the
.Values irregardless.
pkg/app/two_pass_renderer.go
- Migrated to use finalEnv.GetMergedValues()
pkg/environment/environment.go
- Introduced GetMergedValues, which merges the environment's defaults
and current values, and then casts the keys to string;
This was previously defined in HelmState.Values() - however, as this
method is only concerned with the environment, I think it's more
appropriate for it to sit here.
pkg/state/state_exec_tmpl.go
- Extracted out HelmState.Values() to environment.go, see above
> Fix: populate .Values regardless of prestate success

- go.mod
For GCP Secrets Manager support
> Bump variantdev/vals to v0.4.0

- README.md
Prior to this change, these two examples suggested enclosing a release spec in an `if` expression, which breaks the lock file when switching environments.
This change parameterizes `installed` instead of the entire release, thus preserving the dependency locking functionality.
> Amend examples which broke lock files in README.md

- README.md
- pkg/app/app_test.go
- pkg/app/mocks_test.go
- pkg/exectest/helm.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/state.go
- pkg/state/state_test.go
- createNamespace is a new attribute that can be added to helmDefaults
or an individual release to enforce the creation of a release namespace
during sync if the namespace does not exist. This leverages helm's
(3.2+) --create-namespace flag for the install/upgrade command. If
running helm < 3.2, the createNamespace attribute has no effect.
Resolves #891
Resolves #1140
> Support for createNamespace

- Dockerfile.helm3
As helmfile v0.114.0 has a new `createNamespace` option, it would be good to have it in the Docker image by default.
> Upgrade helm to v3.2.0

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/mocks_test.go
This is for #1213 so that the releases are considered scoped to their namespace and not to tiller namespace.
Note the open question here: https://github.com/roboll/helmfile/issues/1213#issuecomment-621402678
> Use namespace for release unicity with helm3 (#1213)

- pkg/app/app.go
- pkg/app/context.go
- pkg/state/state.go
When install is false, we do not need to update the repositories and get
the chart.
Fix #1232
> Allow skipping chart-related operations when `installed: false`

- main.go
Added a global flag `—debug`  that sets the logging level to debug and passes the global flag `—debug` to Helm through subcommands’ `—args`. See: https://github.com/roboll/helmfile/issues/1104
- Helm accepts the redundancy of the global flag `--debug`
- argparser.GetArgs gets rid of the redundancy which seems to be used to parse all —args
- what do you think about adding an Args field to `state.ReleaseSpec` ?
- what about adding a `Debug` (as we do for `—atomic` and `—wait` e.g.) into `state.HelmSpec` `state.ReleaseSpec` for more granularity ?
- sth still prevents the debug output from being displayed into stdout
- tests
> feat: Add global `--debug` flag for passing `--debug` to helm

- README.md
Fixes https://github.com/roboll/helmfile/issues/1248
This can bite you if you have values that are dynamic, in my case a git sha, where sometimes the templating losses information that a string would preserve. I could see this being a mistake that other people fall into so I wanted to add this note to the docs.
> README: Add note about environment variable types

- README.md
- pkg/state/state.go
This prevents typos in sub-helmfile paths from silently preventing operations from running.
> Error when subhelmfiles do not exist

- pkg/app/desired_state_file_loader.go
Fixes https://github.com/roboll/helmfile/issues/1142
desired_state_file_loader.go
- Will now normalize the content before splitting it to parts
context:
Me & and a fellow dev have tried to figure out why helmfile didn't fill in certain values on his machine; 
turns out, he'd mistakenly checked out our project w/ CRLF line endings, which had caused part splitting to not work (as it's hard coded to look for '\n').
The following was acted on as a single part, causing values from the bases not to be available in the next yaml part:
```
bases:\r\n
- base.yaml\r\n
---\r\n
releases:
- name: external-secrets-crd
... some templated yaml ...
```
I've thought about regex-ing it out instead of replace-all, but benchmarks had shown that a plain replace is faster.
I've also considered splitting by …
> Fixed part splitting for CRLF separated files

- docs/advanced-features.md
- pkg/state/helmx.go
- pkg/state/state.go
- test/advanced/helmfile.yaml
- test/advanced/kustomapp/all.yaml
- test/advanced/kustomapp/kustomization.yaml
- test/advanced/kustomapp2/all.yaml
- test/advanced/kustomapp2/kustomization.yaml
Fixes:
- Do not skip passing values files when releases[].adhocDependencies/jsonPatches/jsonPatches exist
- Fix the bug that resulted in any such release to ignore the chart version number specified in helmfile.yaml
- Fix the issue that kustomization has not been properly chartified when a kustomization is specified on `releases[].chart` but there were no `releases[].strategicMergePatches` and `jsonPatches` specified
This is a follow-up PR for #1172
> fix: Follow-up fixes for #1172

- go.mod
- go.sum
- pkg/state/helmx.go
Probably this has been affecting strategicMergePatches and dependencies as well, as the source of the problem is the underlying common feature called helm-x that previsouly used `helm template --output-dir`, which turned out to be not working as intended.
Ref #1279
> Fix missing resources in `hemlfile template` with jsonPatches

- pkg/helmexec/exit_error.go
- pkg/helmexec/runner.go
- pkg/tmpl/context_funcs.go
Seems like this was a regression since https://github.com/roboll/helmfile/commit/f676c6142520364553c6a574fb976eeb0c31a456 and #1159
Fixes #1258
> fix: Do not include stderr content in result of `{{ exec }}`

- .circleci/config.yml
- .gitignore
- Makefile
- go.mod
- go.sum
- pkg/state/helmx.go
- pkg/state/state.go
- test/diff-yamls.go
- test/integration/charts/helmx/.helmignore
- test/integration/charts/helmx/Chart.yaml
- test/integration/charts/helmx/templates/_helpers.tpl
- test/integration/charts/helmx/templates/configmaps.yaml
- test/integration/happypath.yaml
- test/integration/run.sh
- test/integration/templates-golden/v2/helmx/helmx.all.yaml
- test/integration/templates-golden/v2/httpbin/deployment.yaml
- test/integration/templates-golden/v2/httpbin/service.yaml
- test/integration/templates-golden/v2/raw/resources.yaml
- test/integration/templates-golden/v3/helmx/helmx.all.yaml
- test/integration/templates-golden/v3/httpbin/deployment.yaml
- test/integration/templates-golden/v3/httpbin/service.yaml
- test/integration/templates-golden/v3/raw/resources.yaml
- test/local-helm-diff.go
I was working on a helmfile.yaml that applies json patches to a chart that uses `{{ .Release.Namespace }}` in its templates. ([kube-state-metrics to be precise](https://github.com/helm/charts/blob/ed7c211dc21f8f4435c802782a76ffdf4309e400/stable/kube-state-metrics/templates/_helpers.tpl#L45).)
When I applied it, its value was set to the kube context that was active at the time. 
As the helmfile.yaml had explicitly specified the namespace for the chart, I expected `{{ .Release.Namespace }}` to be resolved to that namespace, not the context's.
I'm new to Go and have a feeling that storing a helper 'script' under `test/` and building it as an executable may not be considered best practice. So: please know that this is coming from a place of ignorance.
Also: will not force-push anymore after I …
> Add integration test for Kustomize inetgration

- go.mod
- go.sum
- Add `version` parameter for Vault provider
- Add `profile` parameter for AWS SSM/SecretsManager provider
= Add `version` parameter for AWS SSM Parameter Store provider
- Add support for app-role authentication when using Vault provider
> Bump variantdev/vals to 0.6.0

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
This PR allows per-release `kubeContext` to override `kubeContext` from `helmDefaults` by moving `helmDefaults`'s context to the first helm arg and lowering it's priority ( last `--kube-context` wins).
Fixes #1244
> Fix kubeContext per release override

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/state/state.go
This is useful for e.g. removing state file names and their hash values out of output dirs so that it can be used easily in a gitops setup. For example, `--output-dir-template mybasedir/{{.Release.Name}}` produces `mybasedir/RELEASE/CHART/templates/*.yaml` for each release in your helmfile.yaml.
> feat: `helmfile template --output-dir-template` for customizing output dirs

- pkg/state/state.go
`disableOpenAPIValidation: true` might be useful for workaround for broken CRDs that is known to be exist in older OpenShift versions, and `disableValidation: true` is confirmed to allow installing charts like prometheus-operator that tries to install CRDs and CRs in the same chart.
Strictly speaking, for the latter case I believe you only need `disableValidation: true` set during the first installation, but for the ease of operation I shall suggest you to always set it.
Obviously turning validation mostly(disableOpenAPIValidation) or entirely(disableValidation) result in deferring any real error until sync time. We need completely client-side validation that is able to read CRDs and use it for validating any CRs to catch any error before sync. But it worth an another (big) issue.
> Note …
> Add disableValidation and disableOpenAPIValidation per release

- pkg/app/app_test.go
- pkg/state/helmx.go
- pkg/state/state.go
This, in combination with #1172, allows you to use `go-getter`-supported URL for K8s manifests on `chart`, so that Helmfile automatically fetches it and then turning it into a temporary local chart, which is then installed by Helmfile as similar as standard Helm charts.
An example usecase of this is to install cert-manager CRDs which is distributed separately from the chart:
```
releases:
- name: cert-manager-crds
chart: git::http://github.com/jetstack/cert-manager.git@deploy/crds?ref=v0.15.2
```
I'm adding this based on discussion with @lukasmrtvy. He was trying to install cert-manager and prometheus-opreator with Helmfile, and this combined with #1373 should do the job. Thanks for the input!
> Add ability to use go-getter for fetching remote manifests directory as chart

- README.md
- pkg/state/state.go
Exmple:
```
releases:
- name: test2
chart: stable/mysql
installed: false
hooks:
- events:
- prepare
- preuninstall
- postuninstall
- cleanup
showlogs: true
command: "echo"
args:
- "event name = {{` {{ .Event.Name `}} }}"
```
Output:
```
helmfile apply
Listing releases matching ^test2$
test2   default         1               2020-07-23 00:51:44.975478 +0900 JST    deployed        mysql-1.6.6     5.7.30
helmfile.yaml: basePath=.
hook[preuninstall] logs | event name =  preuninstall
hook[preuninstall] logs |
Deleting test2
release "test2" uninstalled
helmfile.yaml: basePath=.
hook[postuninstall] logs | event name =  postuninstall
hook[postuninstall] logs |
helmfile.yaml: basePath=.
hook[cleanup] logs | event name =  cleanup
hook[cleanup] logs |
DELETED RELEASES:
NAME
test2
```
Resolves #802
> Add pre/postuninstall hooks

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/context.go
- pkg/app/load_opts.go
- pkg/app/run.go
- pkg/state/state.go
- pkg/state/state_test.go
Changes:
- Prevent Helmfile from unnecessarily running `helm repo add` and `helm repo up` against repositories for unused repositories(repositories of releases filtered out by selector)
- Fixes #1330
>  Fix and enhancement to repository update

- pkg/state/state.go
This fixes a regression introduced in #1388
Fixes #1394
> Fix regression on template failing due to duplicate fetch target

- pkg/state/state.go
Handle `--disable-openapi-validation` parameter in `helm3 upgrade` command 
Fixes #1378
> Handle --disable-openapi-validation parameter in helm upgrade

- pkg/app/app.go
- pkg/app/run.go
- pkg/state/chart_dependency.go
- pkg/state/state.go
- pkg/testhelper/testfs.go
In #1172, we accidentally changed the meaning of prepare hook that is intended to be called BEFORE the pathExists check. It broke the scenario where one used a prepare hook for generating the local chart dynamically. This fixes Helmfile not to fetch local chart generated by prepare hook.
In addition to that, this patch results in the following fixes:
- Fix an issue that `helmfile template` without `--skip-deps` fails while trying to run `helm dep build` on `helm fetch`ed chart, when the remote chart has outdated dependencies in the Chart.lock file. It should be up to the chart maintainer to update Chart.lock and the user should not be blocked due to that. So, after this patch `helm dep build` is run only on the local chart, not on fetched remote chart.
- Skip fetching chart on `helmfile …
> Fix various issues in chart preparation

- README.md
- pkg/app/app.go
- pkg/state/state.go
So that those hooks are executed as intended. The documentation about hooks are enhanced as well to clarify the intended behaviour.
Fixes #1398
> Fix race on/sometimes missing postsync and cleanup hooks

- pkg/state/create_test.go
To ensure that `helmfile -l foo!=bar` does match against release without the label at all.
> Add test case

- pkg/app/app_test.go
- pkg/state/state.go
This reverts a part of #1383 so that repository updates are done in the pre-0.125.0 way, which tries to update any repositories only once regardless of they are referenced by selected releases or not.
Ref #1404
> Revert filtering on repositories to be updated

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
Fixes #1427
Helm binary distribution (in archlinux, at least) does not have patch part it it's `helm version` output. This should be supported by helmfile because patch part is actually never used by any meaningful checks.
I thought that it would be nice to use existing `semver` package of Masterminds or coreos to parse semver instead of regex, but this doesn't make sense since we now support non-semver `v3.3`
Also I noticed that errors are not handled properly, so I refactored `getHelmVersion` just a little bit. Next time when it panics user will get a better idea of what's happening. Not ideal though
> Allow helm versions without patch semver part (#1427)

- go.mod
- go.sum
To fix the issue that adhoc json patches were not working on kustomize/raw manifests.
Note that regular kustomize project was working. In other words, this only affetcts `chart: path/to/dir` combined with `jsonPatches: ...` when the `path/to/dir` points to a kustomize project or a local directory containing raw K8s manifests.
Ref https://github.com/roboll/helmfile/issues/1434#issuecomment-682247709
> Bump chartify to 0.4.2

- pkg/state/state.go
> Fix race while running `helm dep build` on local chart

- pkg/state/create_test.go
- pkg/state/envvals_loader.go
- pkg/state/helmx.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
This adds the ability to utilize `.Release` inside of gotmpl files as discussed [here](https://github.com/roboll/helmfile/issues/760).
Resolves: https://github.com/roboll/helmfile/issues/760
Added a simple test that passed once implemented and all tests are running green.
> feat: Allow .Release.Name to be used in gotmpl values templates

- README.md
- main.go
A simple change to allow the 'environment name' to be set by an environment variable. Precedence have command line option.
> HELMFILE_ENVIRONMENT variable

- README.md
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
This adds `comonLabels` option to helmfile by:
- Adding `CommonLabels` to HelmState
- Changing `markExcludedReleases` and `ListReleases` functions to merge common labels into release labels
Resolves #1266
> feat: common labels for all releases in a helmfile

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/state/release.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl_test.go
This is handy when debugging complex `helmfile.yaml` and `values.yaml.gotmpl` as the resulting `helmfile.yaml` contains all the rendered values and sops-encrypted secrets in its embedded form.
It's gonna be used to resolve a terraform-provider-helmfile issue that requires a unique hash of the desired state: https://github.com/mumoshu/terraform-provider-helmfile/issues/28
Environment values and secrets are not yet supported. They are output as-is. But it should be fine as the resulting helm release won't change as long as release values/secrets are unchanged.
> feat: `helmfile build --embed-values` to embed release values and secrets into the output

- pkg/state/helmx.go
- pkg/state/state.go
This is an experimental feature to support a potential use-case that you need to set namespaces in manifests rendered by `helmfile template`, WHEN the chart is unconventional hence does not have `namespace: {{ .Namespace }}`.
Rather than using this, you should usually fork/maintain or update/pull-request the chart to have `namespace: {{ .Namespace }}`.
Use this only when you CAN NOT do so, but still need to use `helmfile template`.
> Add experimental "forceNamespace" in helmfile.yaml

- go.mod
- go.sum
- pkg/app/desired_state_file_loader.go
- pkg/argparser/args_test.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl_test.go
- pkg/state/state_test.go
- pkg/tmpl/sprig_functions_test.go
I have explictly added mergo 0.3.11 as 0.3.9 is considered broke (see https://github.com/imdario/mergo#important-note , and https://github.com/Masterminds/sprig#important-notes )
The other `go.mod` changes happended automagically - I assume that is a `go mod vendor` doing that
Ref https://github.com/roboll/helmfile/issues/1168#issuecomment-683345472
> Bump sprig to v3.1.0 and mergo 3.11

- pkg/helmexec/runner.go
This happened only when helmfile is run in an environment that any environment variable definition does not include `=` and the right side.
> Fix `index out of range [1] with length 1` error on env2map

- pkg/state/create_test.go
- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
It was accidentally removed in #1424, and had been unexpectedly unavailable between v0.126.0 and v0.128.1.
Fixes #1464
> Re-add Release.Namespace in release values.yaml templates

- README.md
I've made a small change to Global Hooks example in order to remove release name reference - this was probably copy/pasted from Hooks section. As I understand release name can't be referenced in Global Hooks section.
I am not sure if there is any open issue that might be relevant to this PR.
> Update README.md - small change to Global Hooks example  

- pkg/state/state.go
Fix bug where KubeContext is not taken into account in temporary directories.
Fixes https://github.com/roboll/helmfile/issues/1470
> Append KubeContext to temporary directory path

- pkg/app/app_test.go
- pkg/state/release_filters.go
- pkg/state/selector_test.go
Helmfile is defined to treat multiple `-l` as OR and multiple conditions in a single `-l` as AND. But there was a bug that a selector with multiple negations matches on first negation that encountered a missing label, which means it's unexpectedly treated as an OR sometimes. It should iterate over all the negations, not only the first on, regardless of the existence of the label, to be an AND.
Since this change, we can treat all the multi-conditions case AND.
Fixes #1477
> fix: Do treat selector with multiple conditions an AND for negation on a missing label

- .circleci/config.yml
- Dockerfile
- Dockerfile.helm3
- pkg/app/app_test.go
- pkg/app/mocks_test.go
- pkg/exectest/helm.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/state.go
Bump Helm version to the latest as it contains several security fixes.
Ref:
- <https://github.com/helm/helm/releases/tag/v3.3.2>
- <https://github.com/helm/helm/releases/tag/v2.16.11>
> Support the latest Helm (>=v3.3.2) and bump the Helm version in Docker image.

- pkg/state/helmx.go
Hi,
I found `releases[].forceNamespace` doesn't work okay, so tried to fix it.
```sh
$ cat <<EOF > sample-helmfile.yaml
releases:
- name: scaler
forceNamespace: this-is-forced-namespace
chart: stable/cluster-autoscaler
EOF
$ helmfile -f sample-helmfile.yaml template
```
It's gonna insert `metadata.namespace` with value `forceNamespace` if a chart has some manifest templates which doesn't have `metadata.namespace`.
cc @mumoshu
> Fix: forceNamespace needs shouldRun is true

- README.md
Before this, the documentation didn't mention that the release needs to
be prefixed with the namespace if the release had a namespace configured.
> Clarify namespace prefix in needs

- USERS.md
The SettleMint platform allows enterprises to spin up k8s clusters and deploy production-grade blockchain networks and additional services. Helmfile is in charge of deploying these networks and services on demand out of the self-service management UI.
> Add SettleMint to the USERS list

- go.mod
- go.sum
- pkg/app/app_test.go
- pkg/app/mocks_test.go
- pkg/exectest/helm.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/chart_dependency.go
- pkg/state/state.go
- pkg/state/state_test.go
This PR contains 1 bug fix and 1 change:
- Fix the helm version comparison. As @tyrken mentioned in #1493, I'm trying to use the semver package to parse, compare, and process the helm version string.
- Use option `--force-update` in `helm repo add`, ONLY when the Helm version is `>= 3.3.2` and `< 3.3.4` (ref #1489 and helm/helm#8777).
> Append --force-update for specific helm versions.

- go.mod
- go.sum
This fixes the bug that generated Chart.yaml misses the `apiVersion` field which resulted in `helm lint` always failing on the generated chart.
Fixes #1527
> Bump chartify to v0.4.3

- pkg/state/state.go
> Fix intermittent failures while building deps on local chart

- pkg/app/app_test.go
- pkg/app/context.go
- pkg/app/mocks_test.go
- pkg/exectest/helm.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/state.go
- pkg/state/state_test.go
This adds some basic support for helm repositories hosted on azure container registry (not OCI but [classic ones](https://docs.microsoft.com/en-us/cli/azure/acr/helm?view=azure-cli-latest). Add a new element to RepositorySpec to state that is externally managed and runs the az-cli command instead of the helm one.
> Support for azure acr helm repositories

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
While using the `--debug` option, the output of helm seems to be printed triple times:
```
Templating release=test, chart=charts/test
exec: helm template test charts/test --namespace staging --values /tmp/values266548685 --output-dir outputs//helmfile-test-staging-ed5e3c94-test --debug
helm:MRAjW> install.go:172: [debug] Original chart version: ""
helm:MRAjW> install.go:189: [debug] CHART PATH: /app/charts/test
helm:MRAjW> wrote outputs//helmfile-test-staging-ed5e3c94-test/test/templates/secret.yaml
helm:MRAjW> wrote outputs//helmfile-test-staging-ed5e3c94-test/test/charts/redis/templates/configmap.yaml
helm:MRAjW> wrote outputs//helmfile-test-staging-ed5e3c94-test/test/charts/redis/templates/health-configmap.yaml
helm:MRAjW> wrote …
```
> Remove duplicated logs from helm.exec.

- go.mod
- go.sum
To incorporate the fix for unconventional chart templates like seen in the Datadog chart https://github.com/variantdev/chartify/commit/5443ca1a1db36d2626522f39130ac1157a69c3f7
> Bump chartify to 0.4.4

- pkg/helmexec/exec.go
See: https://github.com/roboll/helmfile/pull/1542#issuecomment-710082201
Please merge this PR first as currently with Helm v3.3.4, helmfile won't keep the repos updated.
> Retain `helm repo add --force-update` when Helm is v3.3.4 or above

- Dockerfile
- Dockerfile.helm3
As per the [version skew of kubectl](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl) I picked v1.18.9 as to support both the latest stable and as many older versions as possible.
I upgraded Helm because using the latest release I was getting strange issues with helm-diff being unable to unmarshal YAML which I couldn't replicate locally (on the same versions of helmfile, helm, and plugins), but could within the Docker release. Upgrading Helm to the latest patch fixed it for me.
Changes:
* Bump helm to v3.3.4.
* Bump kubectl to v1.18.9
* Update Dockerfile to be a little more verbose to help understand which command in a chain failed.
Signed-off-by: Jake Hill <jake@naphta.uk>
> feat: Upgrade kubectl, upgrade helm

- README.md
Documentation improvement - took some time for me to realise that `devel` should be used instead of `args` to enable pulling development versions of charts from harbor:
- Fixing README
> fix: README improvement

- pkg/state/state.go
Issue created in #1551
When `helmfile template` includes other helmfiles using glob and the directory and helmfiles do not exist, an error message is printed to stdout together with rendered k8s resources, which makes it impossible to use without manipulation with tool like `kubeval` for example.
Example piece of code in `helmfile.yaml`:
```yaml
helmfiles:
- envs/{{ .Values.Environment.Name }}/helmfile-*.yaml
```
Which may produce something like:
```
no matches for path: envs/default/helmfile-*.yaml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
...
```
when `helmfile template` is executed and `envs` directory is empty.
> fix: printing error to stdout together with templated resources

- pkg/app/app.go
I had mistakenly inverted the necessary flag to turn off the legacy processing on selectors that should be used only for helmfile commands that does not support DAGs/needs.
Fixes #1552
> Fix `helmfile --selector x=y template` with `needs`

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/state/state.go
This allows you to use helmfile-template output as a GitOps source, when the template output contains CRDs and you use Helm 3.
Helm 3 by default removes CRDs from the template output. If you want to git-commit helmfile-template containing CRDs for GitOps and you use Helm 3 for templating, the only way is provide this newly added `--include-crds` flag.
> feat: Add `helmfile template --include-crds`

- README.md
Small update to the readme repository examples since Google is no longer officially supporting hosting the stable/incubator helm charts. The official helm docs are using these repos now, eg. https://helm.sh/docs/intro/quickstart/ and https://github.com/helm/charts.
> Update readme stable/incubator URLs

- main.go
Some of the commands show the incorrect options help text, for example `helmfile deps -h`:
```
...
OPTIONS:
--args value                   pass args to helm exec
--skip-repos helm repo update  skip running helm repo update before running `helm dependency build`
```
The trailing `helm repo update` after `--skip-repos` shouldn't be there.
The reason is that the CLI library `urfave/cli` has a feature called "placeholder values". If we backquote a string in the option usage, it will be considered as a "placeholder" for the value of that option.
This PR corrects the help text by replacing the backquotes with double-quotes:
```
...
OPTIONS:
--args value  pass args to helm exec
--skip-repos  skip running "helm repo update" before running "helm dependency build"
```
> Fix incorrect help text of some CLI options.

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/remote/remote_test.go
- pkg/state/create.go
- pkg/state/create_test.go
- pkg/state/state.go
- pkg/state/state_test.go
- pkg/testhelper/testfs.go
`helmfile.yaml`:
```yaml
repositories:
- name: bitnami
url: https://charts.bitnami.com/bitnami/
releases:
- name: example # this chart contains a dep
chart: ./charts/example
```
`./charts/example/Chart.yaml`:
```yaml
apiVersion: v2
name: example
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
- name: redis
version: ^10.7.0
repository: alias:bitnami
```
When I run `helmfile deps --skip-repos` with the helmfile.yaml above, it skips updating the deps of the local chart `example`:
```
$ helmfile deps --skip-repos
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information.
```
What I was …
> Fix the logic of helmfile deps and add tests.

- pkg/helmexec/context.go
- pkg/helmexec/exec.go
- pkg/state/state.go
`helmfile-diff` sorts multiple and concurrent helm-diff outputs and stabilizes writes to stdout.
It's required to use the stdout from helmfile-diff to detect if there was change(s) between 2 points in time.
For example, terraform-provider-helmfile runs a helmfile-diff on `terraform plan` and another on `terraform apply`.
`terraform`, by design, fails when helmfile-diff outputs were not equivalent, meaning that the plan is outdated and the user needs to rerun `terraform plan` against the live state.
Unstable helmfile-diff outputs results in this terraform's outdated-plan-detection to unexpectedly triggered, even if there were no changes in the helmfile.yaml/templates/manifests and the cluster's live state. Stabilizing helmfile-diff output fixes that.
> Stabilize helmfile-diff output

- pkg/state/state.go
To keep a more minimalist helmfile when we're serializing our helmfiles to from programs to disk it would be nice to keep them with a trimmed set of fields
> chore: suppress empty values on serializing several helmfile values

- examples/README.md
The current example in the documentation for using the selector flag doesn't work. It looks like the order matters.
`helmfile sync --selector job=dbmigrator` gives me `Incorrect Usage: flag provided but not defined: -selector`.
> Fix selector syntax in example

- pkg/state/create.go
- pkg/state/state.go
When `helmDefaults.tillerNamespace` is set, helmfile will append `--tiller-namespace` to the helm flags regardless of the helm version.
> Don't append --tiller-namespace flag when running helm3

- go.mod
- go.sum
- pkg/state/state.go
- pkg/state/temp.go
- pkg/state/temp_rand.go
- pkg/state/temp_test.go
This finishes the work started at #1619 by introducing the following changes:
- You can now set `HELMFILE_TEMPDIR` and `CHARTIFY_TEMPDIR` as the directory to persist temporary values files rendered by helmfile and temporary charts generated by chartify. Note that chartify is used internally when you use kustomize integration or raw K8s manifests as a chart.
- Helmfile uses the hash sum of the release config and the values file content in the file name of the temporary values file.
In combination with `HELMFILE_TEMPDIR` and `CHARTIFY_TEMPDIR`, this enables helmfile to use the stable file names for temporary values files, which contribute to stabilize log messages like `Comparing release=appset, chart=PATH/TO/TEMPORARY/CHART`, where the `PATH/TO/TEMPORARY/CHART` had been randomized due to …
> feat: Stabilize helmfile-diff output

- README.md
Adding documentation for this feature: https://github.com/helm/helm/pull/6819
not being aware of this, make turn helm2 to 3 migrations very complicated.
> Adding documentation for PR #6819

- Dockerfile.helm3
In order to use the newly included Kustomize Transformers functionality (#1592), I propose to include the `kustomize` binary in the Docker image.
I understand that it will make the image size significantly larger, but is that a problem?
The alternative would be to provide another flavor of the image, e.g. `helm3-kustomize-v0.135.0`, but is it worth the hassle?
> Include kustomize binary in helm3-based Docker image

- go.mod
- go.sum
For Azure KeyVault support for the fix for AWS SSM provider.
> Bump variantdev/vals to 0.12.0

- pkg/helmexec/exec.go
Password is already being sent via stdin, so change the args to use password from stdin, and don't send password via args
> fix: dont sent RegistryLogin password via args

- Dockerfile.helm3
Since the latest helm releases some new features, I'm bumping it to `v3.5.0`.
> Bump Helm to v3.5.0.

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/state/state.go
Fixes https://github.com/roboll/helmfile/issues/64
This PR gives the ability to append `--wait` to either `helmfile sync` or `helmfile apply`.  The setting will append `--wait` to every `helm upgrade ...` command and it will also override helmDefaults and per-release settings.
> Add ability to specify / override helmDefaults.wait via cli

- pkg/app/run.go
- pkg/state/state.go
When the same release name is used accross namespaces/kubecontexts
a bad chart name could be used
fixes #1694
> fix bug #1694

- README.md
- replace deprecated helm-secrets with the active helm-secrets
```plain
Deprecation Info
Please note, this project is no longer being maintained.
Link to active helm-secret plugin could be found in helm documentation: https://helm.sh/docs/community/related/#helm-plugins
```
> Update helm-secrets in README.md

- Dockerfile
- Dockerfile.helm3
- README.md
- docs/remote-secrets.md
Minor reference fix to the latest place to find helm-secrets.
Tested the plugin myself and works without an problems.
Resolves https://github.com/roboll/helmfile/issues/1632
> Update reference for helm-secrets to latest maintained fork

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/formatters.go
Please squash.
Motivation:
I want to make a command to `helm pull` all charts to have a local version to debug.
```
for row in $(helm list --output json | jq -r '.[] | {chart: .chart, version: .version} | @base64' | uniq); do
chart=$(echo ${row} | base64 -d | jq -r '.chart');
version=$(echo ${row} | base64 -d | jq -r '.version');
echo "Downloading ${chart} ${version}";
helm pull ${chart} --version ${version} --untar --untardir debug/charts/${chart}/${version} || :;
done
```
> (feat) Add chart & version to list cmd

- README.md
- docs/writing-helmfile.md
- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/helmexec/exec_test.go
- pkg/state/state.go
- pkg/state/state_test.go
- pkg/state/temp_test.go
Fixes https://github.com/roboll/helmfile/issues/1650, https://github.com/roboll/helmfile/issues/785
This PR adds:
- `--wait-for-jobs` CLI override option to helmfile binary
- `waitForJobs` helmDefaults parameter (default `false`)
- `waitForJobs` release parameter (default `false`)
`--wait-for-jobs` was introduced in Helm3.5 ( https://github.com/helm/helm/pull/8363 )
> Enable --wait-for-jobs flag introduced in helm3.5

- README.md
- pkg/state/environment.go
- pkg/state/state.go
This PR add the support for kubeContext in environments configuration, it resolves #898 
If a kubeContext is specified in the release this kubeContext is used instead of the one defined in the environment.
> Add support for kubeContext in environments

- pkg/helmexec/exec.go
This fixes #1691 by redirecting helm-template output to our logger when and only when --output-dir is being passed to helm-template.
See https://github.com/roboll/helmfile/pull/1691#issuecomment-805636021 for more context.
> Fix helmfile-template not writing to stdout

- main.go
- pkg/app/app.go
- pkg/app/config.go
- pkg/app/run.go
- pkg/state/state.go
- pkg/state/temp_test.go
Should the temporary directory for charts download be $HOME/.helmfile/cache for commands like `lint`?
> (feat) add fetch command to download charts for debug

- pkg/app/desired_state_file_loader.go
This would allow cli flag `--kube-context` to override value in helmDefaults allowing to use different values in local development and CI context.
> fix: make --kube-context override helmDefaults

- main.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/diff_test.go
- pkg/app/run.go
- pkg/state/state.go
- pkg/state/state_test.go
This PR adds --show-secrets argument on the diff and apply commands that is useful for debugging purposes.
Resolves #1674
> feat: --show-secrets on diff and apply commands

- pkg/event/bus.go
- pkg/event/bus_test.go
This PR allows the use within hooks of snippets like those below to simplify inclussion of `kubectl apply` commands
```yaml
kubectlApply:
kustomize: kustom
---
kubectlApply:
filename: resource.yaml
```
> Add `kubectl` hooks for applying file(s) or kustomize

- go.mod
- go.sum
We use kustomize in two places. One for turning kustomize into a chart, and another for patching manifests and the chart.
This fixes the former to work with kustomize v4.
Fixes #1688
> Add support for kustomize v4

- go.mod
- go.sum
Manually verified to work by using the following example from @damoon (https://github.com/roboll/helmfile/issues/1655#issuecomment-801122431):
```
repositories:
- name: prometheus-community
url: https://prometheus-community.github.io/helm-charts
releases:
- name: metrics
namespace: monitoring
chart: prometheus-community/kube-prometheus-stack
version: 13.13.0
jsonPatches:
- target:
version: v1
kind: Service
name: metrics-kube-prometheus-st-kube-etcd
namespace: kube-system
patch:
- op: replace
path: /spec/ports/0/port
value: "2381"
- op: replace
path: /spec/ports/0/targetPort
value: "2381"
```
Before this fix:
```
$ helmfile template
(snip)
COMBINED OUTPUT:
Error: found in Chart.yaml, but missing in charts/ directory: kube-state-metrics, prometheus-node-exporter, grafana
```
After this fix: …
> Fix chartify not to fail on a chart with dependencies

- go.mod
- go.sum
- main.go
- pkg/app/app.go
- pkg/app/app_apply_test.go
- pkg/app/app_sync_test.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/diff_test.go
- pkg/state/state_run.go
Currently, this is going to be a breaking change for whoever relied on the helmfile's existing behavior of `helmfile -l foo=bar apply` silently ignoring the unfulfilled `needs`.
Since this change, for example, `helmfile -l name=myapp apply` with the below helmfile.yaml would fail and require you to add either `--include-needs` or `--skip-needs` to make it successful:
```
releases:
- name: myapp
chart: charts/myapp
needs:
- mydb
- name: mydb
chart: charts/mydb
```
- `helmfile template` defaults to `--skip-needs=true` + `--include-needs=false` assuming the primary use of `helmfile template` is piping to `kubectl apply` and Argo CD, or saving to the disk.
- `helmfile diff`, `helmfile sync`, and `helmfile apply` defaults to `--skip-needs=false` + `--include-needs=false` assuming the user …
> Add --{include,skip}-needs to various helmfile commands

- go.mod
- go.sum
This version fixes that chartify not to fail when the target chart misses `templates` directory.
> Bump chartify to 0.8.1

- pkg/state/state.go
Chartify logs are very _chatty_ and stands out event in quiet mode. This PR moves them to debug to hide chart building process in normal output.
> feat: moved chartify logs to Debug

- go.mod
- go.sum
- pkg/state/helmx.go
> Fix chartify not to break when two or more releases sharing the same chart and the namespace, but kubeContext

- main.go
- pkg/app/app.go
- pkg/app/config.go
- pkg/app/destroy_test.go
This also adds `--skip-deps` to `helmfile destroy`, `helmfile delete`, and `helmfile test` for whoever wants the previous behaviour, when one exactly knows that they don't need to download local chart's dependencies(already downloaded beforehand, or included in the git repo, etc).
Fixes #1800
> Fix destory, delete, and test to work with chartify on local chart with dependencies that are not yet downloaded

- pkg/app/context.go
- pkg/state/state.go
Trying to `helm repo add` the same Helm chart repository to Helm V2 and V3 in a single Helmfile run had been resulting in an incomplete result, only the latter `helm repo add` being skipped. This fixes that.
Fixes #1815
> Fix repo sync to work on repos duplicated between helm v2 and v3

- pkg/app/app.go
- pkg/app/app_apply_test.go
- pkg/app/app_test.go
- pkg/app/destroy_test.go
- pkg/app/diff_nokubectx_test.go
- pkg/app/diff_test.go
- pkg/app/snapshot_test.go
- pkg/app/testdata/testapply_2/deduplicate_by_--selector/log
- pkg/state/state.go
- pkg/state/state_run.go
#1772 broke `--selector` with `needs` in many ways.
The two biggest problems I've encountered were:
- duplicate releases even if you've provided a proper `selector` to deduplicate
- sync/deletion ordering broken when you have `needs`
For the first issue, we had to update `getSelectedReleases` function to also calculate the "selected releases and releases needed by the selected releases", and use that to calculate the DAG. That should have been done in #1772.
The latter started happening after I've fixed the first issue. The source of the issue was that `needs` turned out to be ambiguous in a few cases.
Previously, `needs: ["foo/bar"]` had two meanings. One for "needs release bar in kubecontext foo", another for "needs release bar in namespace foo".
Moreover, `needs: ["foo/bar/baz"]` had …
> Fix --selector to correctly deduplicate releases

- main.go
Ref https://github.com/roboll/helmfile/issues/1830#issuecomment-835632716
Ref #1692
Follow-up for #1772
> Make `--skip-needs=true` the default option

- main.go
- pkg/app/app.go
Changes `helmfile lint` to not stop on the first helm-lint error. It now aggregates helm-lint errors and produce the summary of errors at the end.
```
$ helmfile lint
*snip*
Failed with 1 errors:
Error 1:
command "/home/mumoshu/bin/helm" exited with non-zero status:
PATH:
/home/mumoshu/bin/helm
ARGS:
0: helm (4 bytes)
1: lint (4 bytes)
2: brokenchart (11 bytes)
ERROR:
exit status 1
EXIT STATUS
1
STDERR:
Error: 1 chart(s) linted, 1 chart(s) failed
COMBINED OUTPUT:
Error: 1 chart(s) linted, 1 chart(s) failed
==> Linting brokenchart
[ERROR] Chart.yaml: apiVersion 'v0' is not valid. The value must be either "v1" or "v2"
[INFO] Chart.yaml: icon is recommended
[ERROR] Chart.yaml: chart type is not valid in apiVersion 'v0'. It is valid in apiVersion 'v2'
```
Fixes #1826
> Fix helmfile-lint not to stop on fisrt error

- pkg/state/helmx.go
v0.139.3
```
err: [release "pinpoint": fetching "git::https://github.com/pinpoint-apm/pinpoint-kubernetes.git@pinpoint?ref=master": get: error downloading 'https://github.com/pinpoint-apm/pinpoint-kubernetes.git?ref=master': CreateFile .helmfile\cache\pinpoint\git::https:\github.com\pinpoint-apm\pinpoint-kubernetes.git@pinpoint?ref=master\https_github_com_pinpoint-apm_pinpoint-kubernetes_git.ref=master: The filename, directory name, or volume label syntax is incorrect.; CreateFile .helmfile\cache\pinpoint\git::https:\github.com\pinpoint-apm\pinpoint-kubernetes.git@pinpoint?ref=master\https_github_com_pinpoint-apm_pinpoint-kubernetes_git.ref=master: The filename, directory name, or volume label syntax is incorrect.]
...
Path error in windows
```
Cache dir: …
> cache path issue on Windows

- pkg/state/create.go
There appears to be a simple typo that prevents Helmfile from correctly reporting an error when a secrets file cannot be decrypted (e.g. with sops). Instead, empty values are silently substituted into the rendered template.
> Fix Helmfile swallowing secrets decryption errors

- pkg/state/state.go
The below now works:
```
releases:
- name: pinpoint
chart: git::https://github.com/pinpoint-apm/pinpoint-kubernetes.git@pinpoint?ref=master
```
Trying to use chartify with go-getter on a broken chart might require you to add `skipDeps: true`, as originally intended in #1548:
```
repositories:
- name: linkerd
url: https://helm.linkerd.io/stable
releases:
- name: linkerd
chart: linkerd/linkerd2
version: "2.8.1"
skipDeps: true
forceNamespace: linkerd
values:
- global:
identityTrustAnchorsPEM: aaa
identity:
issuer:
crtExpiry: foobar
tls:
crtPEM: foo
keyPEM: bar
```
Fixes #1847
> fix: Do not fail on deps when chart is fetched by go-getter

- pkg/app/app.go
- pkg/state/state.go
While debugging #1857 I realized that `--skip-cleanup` and `--retain-values` didn't have effects on values files passed to chartify. This fixes that.
> Fix --skip-cleanup to work with chartify

- go.mod
- go.sum
Fixes #1857
Ref https://github.com/variantdev/chartify/commit/8453c41422d62d1d547c96299dac9267c090f9fb
> Fix chartify inability to disable chart dependency

- go.mod
- go.sum
- test/integration/issue.1857.yaml
- test/integration/issue.1867.yaml
- test/integration/run.sh
Fixes https://github.com/roboll/helmfile/issues/1867
Also see these changes in chartify: https://github.com/variantdev/chartify/compare/8453c41422d62d1d547c96299dac9267c090f9fb...ac3f04370d46bd585eef02d2082fd79e47a9aa4c
> Fix chartify regression of missing chart dependencies

- .circleci/Makefile
- .circleci/config.yml
- Dockerfile.debian
- Makefile
- Add debian image based on `stable-slim`, desire for this is largely
around my use case using Azure DevOps which makes it challenging to
use images which are not glibc based.
- Drop support for helm2 in the docker images. This is a tricky one but
given that I was having errors during the docker build for helm2 and
the fact that it has been EoL for a long time now made me think that
this was the correct move.
- As a "while I'm in here" I've upgraded kubectl and helm. I've popped
on the most current patch of the last release (v1.20.3) to give a
slightly broader support for different Kubernetes versions.
- Reworked CI to support pushing a debian and alpine base, and dropped
support for the helm2 versions.
> Add debian docker image, drop helm2, and upgrade packages.

- README.md
I had difficulties loading remote value files even after looking at the docs here and go-getter.
The solution was in the test code here: 
https://github.com/roboll/helmfile/blob/ae942c5288895c84c79171e5446773e4cb41c4ce/pkg/remote/remote_test.go#L67
Use an `@` to separate the path from the GIT url... 
To help others I want to update the docs with the solution which worked for me ;-)
> Add more examples for remote env value files

- .circleci/config.yml
It turned out the Helm 2.17.0 binary is nowhere now. I considered a bit about checking for a newer Helm 2.x releases as an alternative but I resisted as it is almost a year since EoL of Helm 2. Thanks Helm 2. Long live Helm 3!
> Stop integration test for Helm 2.17.0

- go.mod
- go.sum
Fixes #1954
Ref https://github.com/variantdev/chartify/commit/0b1378d379b91a5a1f60132ad80ff8dd3f91f447
> Fix json patches and strategic patches to do work when there was only one resource in the targeted chart/directory

- pkg/state/state.go
This fixes the bug by not including provided values files in the array of generated values, which is evaluated in a deferred block.  
Resolves #1904
> bug: write-values deletes provided --values files.

- README.md
As we are using "environments" all over the place this allows to add
clarity
> readme: fix wrong paths for environments on conf example

- pkg/app/desired_state_file_loader.go
- pkg/state/create.go
- pkg/state/create_test.go
- pkg/state/envvals_loader.go
- pkg/state/envvals_loader_test.go
Currently it's not possible to use `.Environment` values in `*.gomtpl` files. The documentation states the opposite: 
https://github.com/roboll/helmfile#environment (2nd paragraph).
The problem is already described in #1090.
This PR fixes this bug.
Fixes #1090
> Make .Environment values available in .gotmpl files.

- go.mod
- go.sum
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/diff_nokubectx_test.go
- pkg/app/diff_test.go
- pkg/state/state.go
- pkg/state/state_run.go
Helmfile kindly fails with a friendly error when you made a typo in a `needs` entry, i.e. a `needs` entry to an undefined release triggers an error, instead of silently running the helmfile command with a wrong DAG.
Example Output:
```
in ./helmfile.needs.yaml: release(s) "app" depend(s) on an undefined release "infrastructure/cert-manager2".
Perhaps you made a typo in `needs` or forgot defining a release named "cert-manager2" with appropriate
`namespace` and `kubeContext`?
```
This prevents issues like #1959
> Do fail on a possible typo in `needs` entries

- pkg/app/desired_state_file_loader.go
> Add go-getter support to load base helmfiles

- go.mod
- go.sum
This PR updates hashicorp/go-getter to v1.5.9
Resolves #1981
> Bump hashicorp/go-getter dependency to v1.5.9

- Makefile
Adds a `darwin/arm64` release artifact compatible with m1 macs.  
I tested this out via circleci and was able to generate the `darwin/arm64` build just fine:
```
#!/bin/bash -eo pipefail
make tools
go mod vendor
ORG=mhuber BUILD_URL="$CIRCLE_BUILD_URL" make cross
go get -u github.com/tcnksm/ghr github.com/mitchellh/gox
go: downloading github.com/mitchellh/gox v1.0.1
go: downloading github.com/tcnksm/ghr v0.14.0
go: downloading github.com/hashicorp/go-version v1.3.0
go: downloading github.com/mitchellh/iochan v1.0.0
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/tcnksm/go-latest v0.0.0-20170313132115-e3007ae9052e
go: downloading github.com/Songmu/retry v0.1.0
go: downloading github.com/tcnksm/go-gitconfig v0.1.2
go: downloading …
```
> Support apple silicon (m1 mac) builds

- README.md
- pkg/app/app_test.go
- pkg/state/state.go
To be able to use `helmfile template` to render helm charts for cluster with other than the default Kubernetes version in helm you might need to add the --kube-version flag to helm. This adds that functionality.
> feat: Option to pass kubeVersion to helm template

- examples/charts/argocd-helmfile-deployment/Chart.yaml
- examples/charts/argocd-helmfile-deployment/README.md
- examples/charts/argocd-helmfile-deployment/argocd.dockerfile
- examples/charts/argocd-helmfile-deployment/helmfile.yaml
- examples/charts/argocd-helmfile-deployment/templates/argocd-ingress.yaml
- examples/charts/argocd-helmfile-deployment/templates/dockerpullsecrets.yaml
- examples/charts/argocd-helmfile-deployment/templates/git-secrets.yaml
- examples/charts/argocd-helmfile-deployment/templates/harbor-secrets.yaml
- examples/charts/argocd-helmfile-deployment/templates/vault-secrets.yaml
- examples/charts/argocd-helmfile-deployment/values.yaml
* Add an example deployment for using ArgoCD with Helmfile, private chartmuseum, private Vault server and private Git repository simultaneously.
> Added example ArgoCD + helmfile deployment

- Dockerfile
- Dockerfile.helm3
Hi,
as discussed in this issue  https://github.com/roboll/helmfile/issues/1134, I propose to allow all users to go through root directory to be able to use helm plugins in container running as non root users.
> Allow users other than root to use helm plugins

- go.mod
- go.sum
Fixes https://github.com/roboll/helmfile/issues/1646
This will allow us to use the new `fromJson` and `mustFromJson` functions
among others.
> Bump sprig library to v3.2.1

- pkg/state/state.go
This fixes https://github.com/roboll/helmfile/issues/1272.
Our use-case for this is: If `postsync` or `cleanup` script fails, this means that a deploy should be marked as failed. Without this fix, this is impossible to detect unless you go and review logs.
Please review and comment on this behaviour change.
> Set postsync and cleanup error

- pkg/tmpl/context_funcs.go
This PR adds a new templating function called `readDir`. With `readDir` users can read the contents of a specified directory and get a list of all contained files. This is useful when reading a bunch of files from a directory. The following example shows a snippet of a values file for configuring a Logstash deployment. Using only `readFile`, a user must specify each file by hand and adjust this list as the number of files to be read grows.
```yaml
logstash:
configs:
logstash.yml: |
{{- tpl (readFile "config/logstash.yml.gotmpl") . | nindent 6 }}
jvm.options: |
{{- readFile "config/jvm.options" | nindent 6 }}
pipelines.yml: |
{{- readFile "config/pipelines.yml" | nindent 6 }}
pipelines:
beats-log4j.conf: |
{{- readFile "config/pipelines/beats-log4j.conf" | nindent 6 }}
nginx-access.conf: | …
```
> feat: Add ReadDir as a templating function

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/state/state.go
Adds support for `helm template --skip-tests` in the `helmfile template` command. Improves functionality in GitOps tools like ArgoCD.
> Add `--skip-tests` to helmfile template command

- pkg/tmpl/context_funcs.go
This PR fixes an issue brought up by @bhester01 in #1934. I made `ReadDir` a method of `*Context` as suggested by @mumoshu, and that seems to have resolved the issue.
> Fix context of the ReadDir templating function

- main.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/diff_test.go
- pkg/app/run.go
- pkg/state/state.go
- pkg/state/state_test.go
We need to suppress the output of certain Kubernetes API objects in the diff/apply output.
As the helm-diff plugin supports `--suppress` to allow suppression of the values (kubernetes objects) listed in the diff output, with this MR, helmfile also supports using this flag now.
> feat: Add --suppress option for diff and apply commands

- examples/remote/helmfile.yaml
- main.go
- pkg/app/app.go
- pkg/remote/remote.go
- pkg/remote/remote_test.go
- pkg/state/helmx.go
Current behavior:
Artifacts (remote helmfile or chart) are downloaded into `.helmfile` relative to working directory
Proposed behavior:
There artifacts are downloaded and cached in user's  `.cache` directory. Since the caching system is moved out of working directory, new commands are proposed `cache info` and `cache cleanup`
Test with `examples/remote`
```
root@e3f962517cc9:/source/examples/remote# /source/helmfile cache info
Cache directory: /root/.cache/helmfile
- apache
- https_github_com_cloudposse_helmfiles_git.ref=master
root@e3f962517cc9:/source/examples/remote# /source/helmfile cache cleanup
Cleaning up cache directory: /root/.cache/helmfile
- apache
- https_github_com_cloudposse_helmfiles_git.ref=master
```
> Use os.UserCacheDir()/helmfile to store downloaded artifacts instead of relative .helmfile directory

- pkg/state/release_filters.go
- pkg/state/selector_test.go
label selectors now also allows . and / in filter.
Not sure if we should allow more characters? Maybe everything except whitespace?
Fixes #970
> Allow more characters in label selectors

- .circleci/config.yml
- .gitignore
- Makefile
- go.mod
- go.sum
- pkg/state/release.go
- test/e2e/template/helmfile/snapshot_test.go
- test/e2e/template/helmfile/testdata/issue_2098_release_template_needs/input.yaml
- test/e2e/template/helmfile/testdata/issue_2098_release_template_needs/output.yaml
It turned out that Helmfile has never had support for release templates on `needs`.
This adds that, along with the new end-to-end test suite to verify helmfile template output with snapshot testing involving a real `helmfile build` command.
Ref #2098
> Make release template to work on `needs`

- pkg/app/app.go
- pkg/app/app_apply_test.go
- pkg/app/testdata/testapply_2/select_non_existant_release_with_--allow-no-matching-release/log
- pkg/app/testdata/testapply_2/select_single_release_from_helmfile_with_two_duplicates/log
Stops panic when deduplicating releases, and only add release to deduplicated list if the release is in the selectedIds.
Added two testcases for the two issues that mention this problem.
Fixes #2062 
Fixes #2065
> Stop panic when deduplicating releases

- go.mod
- go.sum
This release fixes an issue when you tried to chartify a local chart whose directory name does not match the name of the chart defined in Chart.yaml.
See https://github.com/variantdev/chartify/releases/tag/v0.9.4 for more information.
> Bump chartify to v0.9.4

- pkg/tmpl/context_funcs.go
My use case is to check for file existence before using it with `readFile`, or we might implement `must` functions instead.
For now as a workaround, I'm using something like `if eq "ok" (exec test -f <file> && echo "ok" || echo "ko")` to do the job :-)
> Add template function isFile

- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
- pkg/state/temp_test.go
This adds support for `kube-version` and `api-versions` to be available to `chartify` so that it works even if your release requires `chartify` due to that you use features like `forceNamespace`, `jsonPatches`, `strategicMergePatches`, and so on.
This also enhances `ReleaseSpec` which corresponds to each item of `releases[]` in your `helmfile.yaml` to also accept `kubeVersion` and `apiVersions`, in addition to the top-level `kubeVersion` and `apiVersions` we have today.
The top-level ones works as the default values for release-specific ones. If you have been using the top-level ones, keep using it. It is backward-compatible. If you want to specify it per release, because, for example, your releases are deployed across clusters(in case you differentiate `kubeContext` fields), try the new …
> Enhance support for kube-version and api-versions
