roboll/helmfile

- state/state.go
After using this for awhile I wanted to update the error env var error messages to collect all missing env vars to make using it a little easier to use. I also restructured the error handling in SyncCharts to fix a bug with double logging flag errors.
> Fixed env vars error handling

- state/state.go
> Fix possible race while templating

- main.go
> Fix error on charts.yml fallback

- README.md
So that our user can start leveraging helmfile without too much confusion.
Includes two things:
- A "getting started" guide
- A basic description of the `sync` subcommand
cc/ @xjantoth I've improved the README according to your suggestion at https://github.com/roboll/helmfile/issues/55#issuecomment-373737432.
Would this look good to you? Thanks!
> Improve readme for first-time users

- README.md
> doc: Note about specifying chart semver

- README.md
- examples/README.md
> doc: Add a basic example for managing oneshot jobs

- Dockerfile
- Makefile
Small improvements to the container setup:
* Upgrade to latest alpine version
* Install Helm 2.8.2
* Check SHA256 of Helm
* Add a run command to the Makefile
> Upgrade container to alpine 3.7 and Helm 2.8.2 & check sha256

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
> Update dependencies of local charts when running 'sync'

- state/state.go
> Add envvar interpolation for names and namespaces

- .circleci/config.yml
- Makefile
> Redo release automation via CircleCI

- state/release_filters.go
- state/state_test.go
Currently if I have the following charts
```yaml
- name: pre
labels:
stage: pre
- name: post
labels:
stage: post
- name: other
- name: other2
- name: other3
```
`helmfile -l stage=pre` will install chart pre as expected
`helmfile -l stage!=` will fail with a malformed label selector
`helmfile -l stage!=pre` will install post
After these changes
`helmfile -l stage=pre` will install pre
`helmfile -l stage!=` will install other, other2, other3
`helmfile -l stage!=pre` will install post
Resolves #99
My specific use-case is to be able to do
```bash
helmfile -l stage=pre
helmfile -l stage!=
helmfile -l stage=post
```
Without needing to label all of the non pre/post charts with a stage.
> support selector that is empty

- Dockerfile
> Add root CAs to docker image

- state/state.go
- state/state_test.go
> support relative path for is local check

- .circleci/config.yml
> Fix failing automated release

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
> status command retrieves release status

- README.md
- USERS.md
Created a Google Doc and a markdown file to track production users, resolving #52.
> add users file to track production use

- .circleci/config.yml
Re-add `make tools` removed in #124.
> install ghr for releasing

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
> Fix the helm-diff deprecation warning

- README.md
- helmexec/exec.go
- helmexec/exec_test.go
- helmexec/helmexec.go
- state/state.go
- state/state_test.go
We have a remote repository that requires username and password to authenticate to. This PR enables that basic functionality.
> Add basic repository authentication

- helmexec/exec.go
- helmexec/exec_test.go
> feat: `helmfile diff` also works against non-existent releases

- Dockerfile
> Add helm-secrets plugin to Dockerfile

- main.go
Sorry, I made a mistake :pray:
* [Add the option to specify an alternative helm binary by hori\-ryota · Pull Request \#181 · roboll/helmfile](https://github.com/roboll/helmfile/pull/181)
> Bugfix for helm-binary flag. to global

- main.go
> Fix command descriptions

- main.go
Solves part of https://github.com/roboll/helmfile/issues/111
Adding possibility to pass args to delete command
> Add --args to delete

- main.go
- state/state.go
- state/state_test.go
> feat: Template values files

- state/state.go
- state/state_test.go
> fix: helmfile should fail on duplicate release name

- README.md
> doc: Instruction to use env files

- main.go
- state/state.go
> feat: emit error message containing which release in which helmfile an upgrade failed

- main.go
- state/state.go
Along with the fix for the bug introduced via #217
Resolves #219
> feat: exit code 2 on unmatched selectors

- README.md
> doc: Using helmfile without an Internet connection

- README.md
- state/state.go
- state/state_test.go
> feat: Support for helm's --set-file

- README.md
- state/state.go
- state/state_test.go
> feat: set array

- args/args.go
- args/args_test.go
- main.go
This pull requests takes in account of order for cli provided args
- Separates args to its own package and test for args.
- fixes issue https://github.com/roboll/helmfile/issues/212
> fix for args being reordered

- helmexec/runner.go
> fix: Relative path in KUBECONFIG envvar

- README.md
- state/state.go
> feat: --force, --recreate-pods, --timeout as first-class citizens in helmfile.yaml

- README.md
- state/state.go
- state/state_test.go
> feat: feat: Configurable default values for --verify, --force, --recreate-pods, and --timeout

- README.md
- state/state.go
- state/state_test.go
- tmpl/context.go
- tmpl/funcs.go
- tmpl/funcs_test.go
- tmpl/tmpl.go
- tmpl/tmpl_test.go
> feat: Template functions to replace `set`s

- helmexec/exec.go
Fixes - https://github.com/roboll/helmfile/issues/167
> use temporary file for secret file to prevent deletion collision

- README.md
- main.go
- state/state.go
- state/state_test.go
- tmpl/context.go
- tmpl/file.go
- tmpl/tmpl_test.go
- valuesfile/valuesfile.go
- valuesfile/valuesfile_test.go
> fix: Keep backward-compatibility broken after introduction of values file template

- helmexec/exec.go
> fix: coordinate secret decryption

- README.md
- ask.go
- main.go
This command syncs releases only if there is any difference between the desired and the current state. It asks for an confirmation by default. Provide `--auto-approve` flag after the `apply` command to skip it.
Resolves #205
> feat: helmfile apply [--auto-approve]

- README.md
- state/create.go
- state/environment.go
> feat: Environment Secrets

- state/state.go
- valuesfile/valuesfile.go
> fix: `sync` partially run `helm upgrade` even one of releases failed while loading values.yaml

- helmexec/exec.go
- helmexec/helmexec.go
- main.go
- state/state.go
- state/state_test.go
Hey, 
This PR will do a `helm template` over releases within the helmfile.
It addresses: https://github.com/roboll/helmfile/issues/283
> feat: `helmfile template`

- main.go
> feat(apply): update repos and and deps before running diff

- state/state.go
> fix: Setting concurrency>1 with single release breaks sync

- main.go
- state/state.go
Enhance the `diff` functionality to be able to return affected releases that has any changes,
so that the succeeding `sync` can be run against only the affected releases.
This provides us extra idempotency.
Resolves #277
> feat: `apply` run `sync` against only affected releases

- main.go
- state/create.go
helmfile as of today ensures that all the targeted helmfile.yaml to have the specified environment defined in it.
That is, `helmfile --environment prod -f helmfile.d/ sync` fails if any helmfile under `helmfile.d/` is missing the `production` environment.
This changes the validation logic, so that helmfile fails only when all the helmfiles miss the environment.
Resolves #279
> feat(environment): Allow missing environment in helmfile.yaml, partly

- main.go
Fixes https://github.com/roboll/helmfile/issues/303
> Add missing repos on lint command.

- state/state.go
> fix: concurrency issue in diff and sync

- main.go
> fix: do not panic on invalid yaml

- app_test.go
- main.go
- main_test.go
- state/create.go
- state/create_test.go
- state/state.go
> fix: unexpected `no releases found for any helmfiles` on `helmfiles:` config

- app_test.go
- main.go
> fix: prevent panicing when an undefined environment name was specified via --environment

- state/state.go
> use channel to harvest download results

- main.go
> evaluate helm-binary BEFORE any helm invocation

- README.md
> docs: add precision on what value files will be rendered

- app_test.go
- main.go
> feat: delete in reverse order

- main.go
- state/create.go
- state/state.go
- tmpl/file.go
- tmpl/funcs.go
> fix: readFile and exec should run in the directory the template file resides in

- main.go
> feat: Prompt before delete

- main.go
- state/state.go
> feat: Option to mark release as not installed

- docs/writing-helmfile.md
- state/create.go
One caveat is that it doesn't merge arrays, but rather the latter overwrites the former.
Resolves #254
> feat: Merge multiple docs inside a single helmfile.yaml

- main.go
> fix: Forbid extraneous arguments

- main.go
> fix: --helm-binary does not work with sync when updating repo

- app_test.go
- main.go
- main_test.go
- state/state.go
> feat: `helmfile repos` updates all repos regardless of selector and releases

- README.md
- main.go
Request for user confirmation only when a global `--interactive` flag is provided.
Resolves #354
> helmfile should be non-interactive by default

- README.md
> doc: mark release as installed/uninstalled

- README.md
- main.go
- main_test.go
> fix first pass rendering crash on syntax error

- README.md
- docs/writing-helmfile.md
- tmpl/funcs.go
- tmpl/get_or_nil.go
- tmpl/get_or_nil_test.go
- tmpl/tmpl_test.go
> feat: `get` and `getOrNil` template funcs to allow defaulting in templates

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/imdario/mergo/README.md
- vendor/github.com/imdario/mergo/merge.go
- vendor/github.com/imdario/mergo/mergo.go
Fixes #377
Ref https://github.com/imdario/mergo/pull/81
> fix: incomplete environment values merging

- README.md
I had some trouble working out how to use Environment Secrets, so I made an attempt at making the documentation more clear.
> Improve documentation of Environment Secrets

- README.md
- test/integration/happypath.yaml
* Tiny documentation fixes
* Updated happypath.yaml according to deprecation notice
> Updated documentation related to deprecation of `context` directive

- state/state.go
Fixes #399 
Extracted `normalizePath(string) string` method and applied normalization to `secrets` and `set` directives.
> Added path normalization in `- set` directive.

- README.md
Hello
I'm maintaining AUR package for this project for a couple of months already. I thought it would be nice if this way of installation will be offered in notes.
Thanks.
> Added new installation method via AUR

- main.go
fixes https://github.com/roboll/helmfile/issues/424
note that the "cleanup" hook is already executed as it should
> fix: prepare hook is not executed for diff command

- app_test.go
- main.go
> fix: Relative path in helmfile not relative to file in multi file setup

- main.go
> fix: helmfle should not break when run without `-f`

- main.go
> feat: Automatically update repos on diffing by default

- main.go
> fix: Always getting deprecated warning

- pkg/app/app.go
> fix: absolute paths to helmfiles should work

- tmpl/context_funcs.go
- tmpl/context_funcs_test.go
Add `tpl` template function that looks exactly like helm's one.
Resolves #420
> feat: `tpl` template function

- README.md
- args/args.go
- state/state.go
- state/state_test.go
> feat: Tiller configuration per release

- state/create.go
- state/state.go
- state/state_test.go
> fix: Various helmfile commands should not leave temp values files

- docs/shared-configuration-across-teams.md
removed the 2 products helm files that where identical to only have one.
> doc(team): change the sub-helmfile as template to hopefully make it more clear.

- state/state.go
- state/state_test.go
> fix: helmfile should not complain on missing values files for undesired releases

- pkg/app/app.go
- pkg/app/app_test.go
> Allow the same release name on different tillerNamespaces

- README.md
* Add slack team badge with instructions for joining slack community <br/>[![Slack Community #helmfile](https://slack.sweetops.com/badge.svg)](https://slack.sweetops.com)
* We've been operating independently from `helmfile` [for ~6 months](https://archive.sweetops.com/helmfile/) and it's time to invite everyone who wants to join!
* Helmfile users have asked if there's a community to ask questions (and we have one!)
> Add slack links

- README.md
Believe this would assist with #548
Don't mean to steal anyone's thunder in updating the doc, if anyone wants to take charge on this and replace it please do. All credit to @sgandon
> readme example for failing when values file is missing

- pkg/app/app.go
- pkg/app/app_test.go
Adds .yml support according to https://github.com/roboll/helmfile/issues/565 discussion
> feat: add .yml extension support

- state/state.go
in debug mode, there was an error log display even when there was no error.
Ithis PR fixes this issue.
> fix(sync): make error log showing when error

- state/chart_dependency.go
- state/state_test.go
- test/integration/environment.values.yaml
- test/integration/happypath.yaml
> fix: helmfile panicing on missing lock file

- go.mod
- state/chart_dependency.go
- state/state_test.go
> feat: support for locking the same chart for two or more versions

- main.go
> feat: add --skip-deps for `helmfile lint`

- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer.go
- state/create.go
- state/create_test.go
> fix: gotmpl layer was unable to reference env values from other layers when env!=default

- docs/writing-helmfile.md
- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- state/create.go
> feat: "base" helmfile state gotmpl is rendered with the envvals inherited from the parent

- state/state.go
- state/state_exec_tmpl_test.go
- state/state_test.go
- tmpl/context_tmpl_test.go
> fix scopelint errors / possible races in hooks

- state/state.go
- state/state_test.go
- state/testfs.go
> fix: do not complain on missing values files for undesired release

- README.md
- pkg/app/app_test.go
- state/create.go
- state/environment.go
> feat: inline environment values

- environment/environment.go
- pkg/app/app_test.go
- pkg/app/two_pass_renderer.go
- pkg/maputil/maputil.go
- state/environment_values_loader.go
- state/state.go
> Fix panic related to env values from files and sprig dict funcs

- README.md
Just a one liner in the readme to make it clear there's a `verify` option in the `releases` section 😄
> Document verify in releases

- README.md
> doc: recommend quoting potentially number-like string

- main.go
I will start by making as much as possible code in `main.go` independent from urfave/cli, and this illustrates how we can do that by introducing a Config interface that delegates any config value fetch to urfave/cli. We will implement an cobra/pflag impl of the interface when helmfile finally migrates to cobra.
> chore: first step towards migration to cobra

- pkg/app/app_test.go
- pkg/maputil/maputil.go
> fix: sprig dict funcs are failing on dicts nested under arrays

- Dockerfile
Resolves #435 (Git as chart repository)
Resolves #220 (S3 as chart repository)
Resolves #436 (About bundling helm plugins)
A lot of thanks to @aslafy-z for authoring the awesome helm-git plugin and contributing it to the community!
> feat: bundle helm-s3 and helm-git into container images

- pkg/state/chart_dependency.go
> Sort requirements alphabetically by name.

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
> issue-663: convert path to absolute path when doing `helm secret dec`

- main.go
- pkg/app/config.go
- pkg/app/run.go
- pkg/state/state.go
- pkg/state/state_test.go
> feat: --concurrency for delete and destroy

- USERS.md
* Adding responses from the Google Forms survey in place until now
* Changing instructions to create a PR and removing the link
I took minor editorial liberty to cleanup and clarify the submitted "More Info" section, but did not change the intent.
> Adding user survey responses while switching to PR style

- pkg/app/app_test.go
- pkg/state/chart_dependency.go
- pkg/state/state.go
- pkg/state/util.go
- pkg/state/util_test.go
We unintentionally broke this since #593.
Fixes #675
Fixes #687
> fix: helm chart referenced by http URL

- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
> fix: `helm diff` missing --reset-values

- pkg/helmexec/exec.go
- test/integration/run.sh
> fix: `helmfile template | kubectl apply -f -` should work

- pkg/state/create.go
> fix: do not panic on merging env secrets

- README.md
Closes https://github.com/roboll/helmfile/issues/710
Fixed a couple very small typos also.
> Change link in README to newer tag

- README.md
Sorry, I only changed the link in my last PR, I didn't change the link text. Embarrassing 😳
> Change link in README to newer tag (again)

- go.mod
- go.sum
Needed for new functions and bug fixes
Resolves #733
Resolves #734
> Upgrade sprig 2.20.0 and xstrings 1.2.0

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/run.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/runner.go
- pkg/state/create.go
- pkg/state/state.go
- pkg/state/state_test.go
> feat: add --output-dir on template command

- pkg/app/app_test.go
- pkg/state/state.go
- pkg/state/util.go
- pkg/state/util_test.go
> fix: absolute chart path

- pkg/maputil/maputil.go
> fix: --state-values-set not setting more than first child in nested paths

- USERS.md
> users update

- pkg/app/app_test.go
- pkg/state/state.go
> fix: pass namespace to helm template command

- pkg/state/create.go
Related to #782 - Process the environment secrets in parallel.
> Handle environment secrets concurrently

- docs/writing-helmfile.md
- pkg/state/release.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl_test.go
This is a follow-up for #823
Ref https://github.com/roboll/helmfile/pull/823#discussion_r319712283
> Make advanced templating backward-compatible

- go.mod
- go.sum
Fix #834
Relates to https://github.com/Homebrew/homebrew-core/pull/43728
> Fix apache thrift location issue

- pkg/app/app_test.go
- pkg/helmexec/exec.go
- pkg/state/state.go
Set `HELMFILE_HELM3=1` and run `helmfile` like `HELMFILE_HELM3=1 helmfile ...`.
When `HELMFILE_HELM3` is set, `test`, `template`, `delete` and `destroy` behave differently so that it works with Helm 3.
Note that `helmfile diff` doesn't work as `helm-diff` called under the hood doesn't support Helm v3 yet.
Ref #668
> feat: Experimental Helm v3 mode

- pkg/state/state.go
> allow empty pattern matching and move on

- README.md
- docs/writing-helmfile.md
- pkg/app/app_test.go
- pkg/app/two_pass_renderer_test.go
- test/integration/happypath.yaml
Pull request related to issue #816
> Fix doc values

- pkg/state/state.go
- pkg/state/state_test.go
> fix(helm3): delete/destroy/apply/sync unable to detect releases to be deleted

- pkg/state/state.go
Thanks for the fix @mumoshu, #857 didn't quite fix it completely for me but did get the list function working correctly.  I borrowed your code to make the delete releases function work as expected.
Fixes #853
> Fix delete/destroy

- README.md
Not sure but looks like this is not a bug and is the intended use-case, so added some docs around it, hopefully it makes sense.  Let me know if I need to reword
> doc: Added some detail on how to use override values in helmfiles section

- go.mod
- go.sum
upgrades sprig to 2.22.0 for #883
> upgrade sprig 2.22.0 #883

- USERS.md
users.md: updated to production usage
> users.md: updated to production usage

- README.md
Add a note explaining how to use Azure ACR as a `helm` repository with `helmfile`.
https://sweetops.slack.com/archives/CE5NGCB9Q/p1570021198041900
> Add ACR notes

- pkg/state/state.go
> fix(helm3): `Error: unknown flag: --purge` on deletion via `helmfile sync`

- .circleci/config.yml
- Dockerfile
Relates to https://github.com/Homebrew/homebrew-core/pull/46008
> helm v2.15.2

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/state/state.go
#922 was not sufficient to fix the issue. This is a follow-up for that to actually fix it by deferring to apply the selectors and limiting when to apply selectors.
> fix: Fix --selector to not break `needs`

- pkg/app/app.go
- test/integration/run.sh
> Fix regression since 0.90.0 that Helmfile becomes too slow when there are many releases

- Dockerfile.helm3
> Remove a helm-tiller plugin from a Helm 3 docker image

- README.md
Also, per brew upgrade, https://github.com/Homebrew/homebrew-core/pull/46832, I have also updated the helm dependency to `v3.0.0`
> Update README per v0.92.1 release

- go.mod
- go.sum
To accomodate the fix for https://github.com/variantdev/vals/issues/13
> Bump variantdev/vals

- pkg/app/desired_state_file_loader.go
> Validate on recursion

- go.mod
- go.sum
Sorry it was not working at all :(
See https://github.com/roboll/helmfile/issues/990#issuecomment-557756343 for how this is supposed to work.
Fixes #990
> Fix ref url in values key to actually work

- Makefile
- go.mod
- go.sum
- main.go
- pkg/app/version/version.go
- pkg/state/chart_dependency.go
> feat: Persist Helmfile version in helmfile.lock for version compatibility check

- README.md
- pkg/helmexec/context.go
- pkg/helmexec/exec.go
- pkg/state/state.go
> Add HistoryMax

- Dockerfile.helm3
Just came to it and saw it was out of date; there are a few bugfixes since the last release.
> Upgrade to latest stable Helm 3

- Dockerfile.helm3
Helm 3 got the second patch: https://github.com/helm/helm/releases/tag/v3.0.2
> Upgrade to the latest Helm 3 release

- pkg/state/chart_dependency.go
> Fix `deps` error for helm 3.0.2

- pkg/app/app_test.go
- pkg/state/state.go
- pkg/state/state_test.go
> fix: helmfile destroy does not delete helm releases in status : PENDING_INSTALL

- docs/writing-helmfile.md
> spelling nitpick

- pkg/app/app.go
- pkg/state/state.go
This PR sets command line options for helm test conditionally to helm version.
fixes #1050
> fix test command for helm 3

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/run.go
- pkg/exectest/helm.go
- pkg/helmexec/exec.go
- pkg/helmexec/exec_test.go
- pkg/helmexec/helmexec.go
- pkg/state/state.go
- pkg/state/state_test.go
Add --supress-diff option on apply. Usable for fresh installs when a
lot of output is produces by diff.
Resolves #458
> Add option to suppress diff on apply

- pkg/state/state.go
fixes same as https://github.com/roboll/helmfile/issues/1050 , but for `helmfile status` command.
> Fix status command for helm 3

- USERS.md
Adding American Express as users of this tooling internally in a POC fashion.
> Added to USERS.md

- .circleci/config.yml
- Dockerfile
- Dockerfile.helm3
relates to https://github.com/Homebrew/homebrew-core/pull/50129
Upgrade deps for helmv2, v3 and golang
> Upgrade deps

- README.md
> fix explanation about secrets in .Environment.Values

- pkg/app/app.go
> fix: delete/destroy ordering within directory

- docs/writing-helmfile.md
this caught my eye.  i figured this was simple enough. 🤷‍♂
> the smallest least meaningful change ever

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- test/integration/run.sh
> feat: --detailed-exitcode for `helmfile apply`

- pkg/app/app_test.go
- pkg/state/create_test.go
- pkg/state/state_run.go
This has bugged me for a while, so I finally decided to do something about it.
See also: [Google Ngram: inexistent vs nonexistent](https://books.google.com/ngrams/graph?content=inexistent%2Cnonexistent&year_start=1800&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cinexistent%3B%2Cc0%3B.t1%3B%2Cnonexistent%3B%2Cc0)
> Fix awkward dependency error message

- go.mod
- go.sum
> Bump mergo to 0.3.8

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/app/destroy_test.go
- pkg/app/load_opts.go
- pkg/app/mocks_test.go
- pkg/helmexec/exec.go
- pkg/state/create.go
- pkg/state/state.go
- pkg/state/state_run.go
> feat: `helmBinary` in helmfile.yaml

- pkg/app/app.go
- pkg/app/app_test.go
> Change the `helmfile list` header "INSTALLED" -> "ENABLED"

- pkg/app/desired_state_file_loader.go
- pkg/state/create.go
- pkg/state/create_test.go
This fixes a regression in #1160
> Fix panic while loading environment secrets

- pkg/state/envvals_loader_test.go
- pkg/state/testdata/issues/1168/addons.yaml
- pkg/state/testdata/issues/1168/addons2.yaml
- pkg/state/testdata/values.1.yaml
- pkg/state/testdata/values.2.yaml
- pkg/state/testdata/values.3.yaml
- pkg/state/testdata/values.4.yaml
- pkg/state/testdata/values.5.yaml
This is a follow-up for #1169 and it also relates to #1168
> Add regression tests for environment values merge

- pkg/app/app.go
This fixes the incomplete output - or skipped `helm diff` runs - when `helmfile diff` was run with `--detailed-exitcode` AND two or more releases had non-empty diff.
Fixes #874
> feat: Complete `helmfile diff` output when diff exists

- pkg/state/create.go
- pkg/state/state_exec_tmpl.go
> fix: .Values is missing keys with zero values

- README.md
Added default comments into helmfile.yaml example
fixed some typos
Signed-off-by: Vadim Bauer <vb@8gears.com>
> Update helmfile.yaml example in README

- main.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config.go
- pkg/app/formatters.go
Fix #913 
* Support output as json
* Add new formatters file to handle extrac formatting to its own concern
* New config interface to support list command specification
> New output flag for list command

- README.md
- pkg/state/state.go
Add conditional release support. Fixes #781
> Add conditional release support

- pkg/state/state.go
- pkg/state/state_test.go
- An error is raised if createNamespace is set explicitly and the
helm version being used is not 3.2+
> Enhance createNamespace error handling

- pkg/app/app.go
This fix apply helmfiles in reversed order in destroy action.
Fixes #1192
> Correct ordering between releases and sub-helmfiles on destroy/delete

- go.mod
- go.sum
Upped the version of vals
It now includes vault approle support
> Bump variantdev/vals for Vault AppRole support

- docs/writing-helmfile.md
Great docs overall, found a small typo in the examples.
> Fix typo in writing-helmfiles.md example

- go.mod
- go.sum
- test/advanced/helmfile.yaml
See https://sweetops.slack.com/archives/CE5NGCB9Q/p1590607083301900?thread_ts=1590237129.290300&cid=CE5NGCB9Q
> Fix ignored chart version on patched release

- go.mod
- go.sum
> Bump variantdev/chartify to fix kustomize support

- pkg/app/app.go
- pkg/app/run.go
> Fix repo update timing

- pkg/app/app.go
- pkg/app/diff_test.go
This one is pretty self-explanatory (:
> typo: Fix message for detected diff

- pkg/state/helmx.go
> Fix patching not using release namespace

- README.md
- pkg/app/app.go
- pkg/app/run.go
- pkg/state/state.go
* add top level hooks field to yaml spec
* add functions for global prepare and cleanup events
* call global prepare and cleanup events in withPreparedCharts function
closes #331
> add global hooks

- pkg/app/app.go
- pkg/app/desired_state_file_loader.go
- pkg/app/run.go
- pkg/state/create.go
- pkg/state/create_test.go
- pkg/state/helmx.go
- pkg/state/state.go
- pkg/state/state_test.go
> Do cleanup decrypted env secrets files

- go.mod
- go.sum
To incorporate the tfstate provider fix
Ref https://github.com/roboll/helmfile/issues/505#issuecomment-653848769
> Bump variantdev/vals to 0.7.1

- USERS.md
We have been meaning to create this PR for a while now...
@stefanthorpe @jasonmorganson FYI
> Add Cherre to USERS.md

- go.mod
- go.sum
> Bump variantdev/chartify to 0.3.8

- go.mod
- go.sum
> Bump chartify to 0.3.10

- README.md
> fix: Misleading doc in the environment-values section

- go.mod
- go.sum
> Bump chartify to 0.3.11

- go.mod
- go.sum
Ref https://github.com/variantdev/vals/pull/33
> Bump variantdev/vals for better Variant KV v2 support

- pkg/app/app.go
- pkg/app/run.go
> Fix list failure when patches are used

- USERS.md
Helmfile is a great tool and we are successfully using it in production for a little more than a year. The project infrastructure is fully open and everybody is invited to contribute to it
> Add Jenkins OSS to the list of users

- pkg/state/state.go
> Fix lint to not fail for duplicate release names across ns

- Makefile
- main.go
> Add version sub-command

- pkg/app/app.go
- pkg/app/app_test.go
Helmfile has been incorrectly showing releases with the same name but in different kubeContexts as duplicates. This fixes that.
> Fix false-positive duplicate release with kubeContext

- pkg/app/app.go
- pkg/app/run.go
- pkg/state/state.go
> Fix `helmfile lint` failure when `installed: false`

- pkg/app/app.go
> Add support for selector on `helmfile template`

- pkg/remote/remote_test.go
- pkg/state/helmx.go
- pkg/state/state.go
- pkg/state/state_gogetter_test.go
> Fix go-getter URL in chart to actually work

- pkg/state/state.go
This fixes a regression introduced in #1399
Fixes #1377
> Fix `helmfile template` with Helm 3 ignoring chart version

- pkg/state/state.go
Ref https://github.com/roboll/helmfile/issues/1401#issuecomment-670915272
> Fix chart fetched by go-getter not to fail due to missing dependencies

- pkg/state/state.go
This fixes the regression introduced by #1406 that resulted in `helmfile template` with helm v2 failing when there is any release with `version`.
Fixes #1414
> Fix regression for helmfile template with helm v2 since v0.125.4

- go.mod
- go.sum
> Fix regression installing raw K8s manifests

- pkg/app/app.go
- pkg/app/run.go
- pkg/state/state.go
> Fix regression in helmfile deps

- Dockerfile.helm3
This is needed to support the --disable-validation flag added into
helmfile
> Update to the latest version of helm-diff plugin

- pkg/state/state.go
> Fix kubeContext not taken into account for release uniqueness

- pkg/event/bus.go
- test/integration/happypath.yaml
a137e53 is for reproduction and 7436c82 contains the actual fix.
Fixes #1445
> Fix panic on hook since v0.126.0

- pkg/app/app.go
Ref https://github.com/roboll/helmfile/pull/1415#issuecomment-684139831
> Fix test flake for `commonLabels`

- pkg/app/desired_state_file_loader.go
- pkg/app/destroy_test.go
- pkg/state/state.go
- pkg/state/state_test.go
> Fix wrong deletion order

- main.go
- pkg/app/app.go
- pkg/app/config.go
- pkg/state/state.go
> Add experimental write-values command for writing values files only

- pkg/state/state.go
> Enable release hook template to access .Values

- pkg/app/app.go
- pkg/app/run.go
> Test only enabled and selected releases

- pkg/state/state_test.go
- pkg/state/util.go
- pkg/state/util_test.go
- test/integration/happypath.yaml
> Add support for ChartCenter

- pkg/app/app.go
- pkg/state/state.go
> Fix multiple --set in --args messed up in `helmfile template`

- pkg/app/app.go
- pkg/state/state.go
See 1 and 3 in https://github.com/roboll/helmfile/issues/1460#issuecomment-691863465
> Minor tweaks for `helmfile write-values`

- pkg/app/desired_state_file_loader.go
- pkg/state/create.go
- pkg/state/create_test.go
- pkg/state/selector_test.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
- pkg/state/state_exec_tmpl_test.go
- pkg/state/state_test.go
> Fix concurrent-map-iteration-and-write errors while running release hooks

- README.md
- go.mod
- go.sum
- pkg/state/state.go
> Add a way to disable dependency up when using helm-x/chartify

- README.md
Hi,
I have pushed helmfile to the official Arch Linux repositories. Thanks for your work, I use it in production :)
> mention Arch Linux support

- pkg/app/app_test.go
- pkg/state/state.go
> Fix redundant helm-dep-build and prepare hook regression

- main.go
- pkg/app/config.go
- pkg/app/run.go
- pkg/state/state.go
> feat: Add `helmfile test --logs`

- README.md
Add a description how to install helmfile on openSUSE Tumbleweed or Leap distributions.
> Mention openSUSE packages for helmfile

- Makefile
> fix: support arm binaries

- README.md
Apologies for not getting it right the first time...
> Fix openSUSE repo URL.

- Dockerfile
- Dockerfile.helm3
- README.md
> Add documentation on how to use the docker image

- docs/writing-helmfile.md
* docs: fix typo
* docs: syntax highlight
> docs: fix typo

- README.md
helm delete is now helm uninstall. See https://helm.sh/docs/helm/helm_delete/
> docs: update helm command name

- go.mod
- go.sum
Ref https://github.com/variantdev/vals/pull/42
> Bump variantdev/vals to 0.13.0

- pkg/state/state.go
I have seen various issues related to the OCI repository support recently added to Helmfile.
This is the patch that should fix all the issues Im aware of until now.
If you've seen issues on helmfile v0.138.0x, I'd appreciate it if you could help testing this.
> Fix OCI support

- pkg/remote/remote.go
- pkg/state/helmx.go
- pkg/state/state.go
- pkg/state/state_gogetter_test.go
> Fix error on concurrent go-getter on same URL

- pkg/state/state.go
> fix: pull OCI charts one by one

- README.md
Feel free to comment what else would need to be done to get this merged. Cheers.
> Update README.md to show current CLI Output

- pkg/state/state.go
> panic with clear message

- pkg/state/state.go
> refactor: simplify pull channel from #1706

- pkg/state/state.go
> allow to access oci repos without auth

- pkg/state/chart_dependency.go
> Improve error message on deps resolution error

- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
> Add .StateValues as alias of .Values in releaseTemplateDataRelease

- README.md
- docs/writing-helmfile.md
relates to #1743, #1744, #1734
> add documentation

- main.go
- pkg/app/app.go
- pkg/app/config.go
- pkg/app/desired_state_file_loader.go
- pkg/app/two_pass_renderer.go
- pkg/event/bus.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
> feat: allow override chart in args

- go.mod
- go.sum
- pkg/app/app.go
- pkg/state/state.go
Fixes #1760
Ref https://github.com/variantdev/chartify/commit/d8f7eac17df3e7a77b5e61f5d2fc11fdfa376d52
> Fix chartify to take --include-crds into account

- pkg/state/state.go
Ref https://github.com/roboll/helmfile/issues/809#issuecomment-814423653
This is not what had been originally requested in #809 but anyway- This enables you to limit helm-dep-up run by helmfile-deps by selector. For example, `helmfile -l name=foo deps` should result in only the release named `foo` to be helm-dep-uped.
> Enable helmfile-deps to limit helm-dep-up by selector

- pkg/app/app.go
> Fix `helmfile repos` to not fail with `forceNamespace`

- pkg/event/bus.go
> Fix some hook log not honoring log level

- pkg/app/app.go
- pkg/app/config.go
- pkg/app/diff_test.go
Follow-up for #1771
Ref #1770
Ref https://github.com/roboll/helmfile/pull/1771#issuecomment-817399338
> Fix --skip-crds not working with chartify

- pkg/state/state_run.go
> Fix destroy not reversing the order of releases

- pkg/app/destroy_test.go
I was curious if destroy with a selector is working at all while reading https://github.com/roboll/helmfile/issues/1750#issuecomment-823521572. So I added this test for verification.
From what I can see from the test result, it is working, though.
> Add test for helmfile-destroy with selector

- pkg/app/app_apply_test.go
- pkg/app/app_sync_test.go
- pkg/app/app_test.go
- pkg/app/destroy_test.go
- pkg/app/diff_test.go
- pkg/exectest/helm.go
- pkg/state/state.go
- pkg/state/state_test.go
`helmfile destroy` and `helmfile delete` was ignoring releases of `uninstalling` statuses. This fixes that.
Ref https://github.com/roboll/helmfile/issues/1750#issuecomment-823677950
> Fix delete on release of `uninstalling` status

- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
> fix: can't evaluate field KubeContext in type state.releaseTemplateDataRelease

- pkg/app/app_apply_nokubectx_test.go
- pkg/app/app_apply_test.go
- pkg/app/app_sync_test.go
- pkg/app/app_test.go
- pkg/app/destroy_nokubectx_test.go
- pkg/app/destroy_test.go
- pkg/app/diff_nokubectx_test.go
- pkg/app/diff_test.go
- pkg/state/state.go
- pkg/state/state_run.go
> fix: spec.KubeContext does not fallback to HelmDefaults.KubeContext

- go.mod
- go.sum
Fixes #1680
Ref https://github.com/variantdev/chartify/commit/8ff30374cb2a65af5167f3d47df81fe45d37b01d
> Fix adhoc dependencies not working with remote chart

- go.mod
- go.sum
- pkg/state/helmx.go
- pkg/state/state.go
Fixes #1681
Ref https://github.com/variantdev/chartify/commit/286ed08a273d4229989aea5ac5c901612b43944c
> Fix --set and --set-file flags are not passed to chartify

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/desired_state_file_loader.go
- pkg/state/state.go
- pkg/state/state_exec_tmpl.go
- pkg/state/types.go
Hi,
I fixed the behavior of defaulting and overriding kubeContext which is discussed in #1810.
It seems that primary issue of #1810 also solved by defaulting kubeContext properly.
> fix defaulting and overriding kubeContext

- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/diff_nokubectx_test.go
- pkg/app/diff_test.go
- pkg/state/state_run.go
> Fix --selector to correctly deduplicate releases

- pkg/app/app_test.go
- pkg/testhelper/testfs.go
To able to run test on windows
> (fix) filepath on windows

- test/integration/happypath.yaml
- test/integration/secretssops.yaml
As ChartCenter has been shut down.
Ref https://github.com/roboll/helmfile/pull/1829#issuecomment-833330609
> Use the incubator chart repo instead of chartcenter

- pkg/state/state_exec_tmpl.go
related issue: https://github.com/roboll/helmfile/issues/1810#issuecomment-833268566
> fix kubeContext does not globally defaulting its value

- pkg/app/app.go
> Fix lint and status not to fail with selector and needs

- main.go
- pkg/app/app.go
- pkg/app/config.go
- pkg/app/diff_test.go
closes https://github.com/roboll/helmfile/issues/1840
> Add --skip-diff-on-install to helmfile diff

- Dockerfile.helm3.ubuntu
- Dockerfile.ubuntu
Implementation of ubuntu based docker image for issue [1783](https://github.com/roboll/helmfile/issues/1783)
> ubuntu docker based image for helmfile

- README.md
See https://github.com/roboll/helmfile/blob/master/pkg/state/state.go#L220
> Fix capitalization of disableOpenAPIValidation config in README

- pkg/app/app.go
- pkg/app/config.go
- pkg/state/state.go
Helpful to debug multiple values files for bad indentation :-)
> add cleanup to write-values & lint to harmonise this flag

- pkg/state/storage.go
> Fix panic on normalizing path containing ..

- pkg/tmpl/context_funcs.go
Ref https://github.com/roboll/helmfile/pull/2058#issuecomment-1019439394
> Fix readdir regression while merging

- Makefile
Signed-off-by: yxxhero <aiopsclub@163.com>
precheck for make test
> precheck for make test

- pkg/app/two_pass_renderer.go
- pkg/state/envvals_loader.go
- pkg/state/types.go
So that the same alias can be used in helmfile.yaml
related to https://github.com/roboll/helmfile/pull/1744
> Add .StateValues as alias of .Values in EnvironmentTemplateData

- pkg/state/state.go
> fix little issue

- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
Ref https://github.com/roboll/helmfile/issues/2148
> Note about the repo move on new issue and pull request
